import type { StoreLanguage } from "./types";
const en = {
  title: "Nico’s Toy Shop", back: "Back to Nico’s World", eyebrow: "FROM NICO’S WORLD", tag: "For grown-ups",
  intro: "Small creations. Big imagination.", description: "A home for Nico’s physical 3D-printed toys. Orders are handled by a grown-up, separate from the games.",
  closed: "We are not accepting orders yet.", open: "Order requests are open. Availability and the final total are confirmed by the adult seller.",
  emptyTitle: "The shop is getting ready", empty: "Real product photos, prices and details will appear here once they have been approved. Nothing is for sale on this page yet.",
  loading: "Checking the shop…", unavailable: "We could not check the current catalog. Ordering is unavailable. Please try again.",
  offline: "You are offline. Any visible catalog details may be out of date. Reconnect and refresh before preparing a request.",
  stale: "These catalog details need refreshing. A request always checks the current details again.",
  retry: "Refresh catalog", collection: "The toy collection", details: "View toy details", imageMissing: "Product photo unavailable. Ordering this item is paused.",
  pricePending: "Price not yet confirmed", each: "per piece", option: "Color / option", choose: "Choose an available option", quantity: "Quantity", subtotal: "Listed item subtotal",
  inStock: "In stock", made: "Made to order", soldOut: "Sold out", paused: "Ordering unavailable", approvalPending: "This item is not available to order yet.",
  dimensions: "Dimensions", material: "Material", care: "Care", preparation: "Preparation time", fulfillment: "Delivery / pickup", safety: "Product safety information",
  physical: "Physical products only — no downloadable print files.",
  adult: "I am a grown-up arranging this order request.", adultNote: "This reminder is not age or identity verification.",
  prepare: "Prepare an order request", preparing: "Checking the latest details…", blocked: "This selection cannot be requested right now. Check the quantity, option and current availability.",
  requestTitle: "Review your request", requestNote: "Opening an email or messaging app does not send a message or confirm an order. Review and send the request yourself. The adult seller will confirm availability, delivery and the final total.",
  email: "Open email to review", whatsapp: "Open WhatsApp to review", copy: "Copy request text", copied: "Request text copied.", copyFailed: "Copy is unavailable. Select and copy the text below manually.",
  fallback: "If your app does not open, copy this text and use the approved business contact shown below.", contact: "Business contact", requestText: "Your request text",
  expiry: "Refresh and prepare a new request when these details expire or change. No requests are sent automatically.",
  requestOnly: "This is an enquiry, not a purchase. Listed item prices are not a final delivery-inclusive total. The seller confirms any applicable charges and taxes before accepting the order.",
  howTitle: "How ordering will work", how1: "Choose a real printed toy and an available option.", how2: "A grown-up reviews and sends a request using the approved business contact.", how3: "The seller confirms availability, delivery and the final total before accepting an order.",
  privacyTitle: "Play stays separate", privacy: "No player names, game progress or creations are included in order requests. No payment details are collected on this page.",
  policies: "Seller and ordering information", territory: "Where orders are accepted", delivery: "Delivery terms", returns: "Returns", privacyPolicy: "Privacy", information: "Seller information",
  pendingPolicies: "Seller contact, delivery arrangements and ordering terms will be published before sales open.",
};
const es: typeof en = {
  title: "La Tiendita de Nico", back: "Volver al Mundo de Nico", eyebrow: "DEL MUNDO DE NICO", tag: "Para personas adultas",
  intro: "Pequeñas creaciones. Gran imaginación.", description: "Un espacio para los juguetes físicos de Nico impresos en 3D. Una persona adulta se encarga de los pedidos, por separado de los juegos.",
  closed: "No estamos aceptando pedidos todavía.", open: "Se aceptan solicitudes de pedido. La persona adulta que vende confirma la disponibilidad y el total final.",
  emptyTitle: "Estamos preparando la tiendita", empty: "Las fotos reales, los precios y los detalles aparecerán aquí cuando estén aprobados. Todavía no hay productos a la venta en esta página.",
  loading: "Consultando la tiendita…", unavailable: "No pudimos consultar el catálogo actual. No es posible solicitar pedidos. Inténtalo de nuevo.",
  offline: "No tienes conexión. Los detalles visibles del catálogo podrían estar desactualizados. Conéctate y actualiza antes de preparar una solicitud.",
  stale: "Es necesario actualizar estos detalles del catálogo. Cada solicitud vuelve a consultar los detalles actuales.",
  retry: "Actualizar catálogo", collection: "La colección de juguetes", details: "Ver detalles del juguete", imageMissing: "La foto del producto no está disponible. Las solicitudes de este artículo están pausadas.",
  pricePending: "Precio por confirmar", each: "por pieza", option: "Color / opción", choose: "Elige una opción disponible", quantity: "Cantidad", subtotal: "Subtotal de productos publicado",
  inStock: "Disponible", made: "Hecho por encargo", soldOut: "Agotado", paused: "No se puede solicitar", approvalPending: "Este artículo todavía no está disponible para solicitar.",
  dimensions: "Medidas", material: "Material", care: "Cuidados", preparation: "Tiempo de preparación", fulfillment: "Entrega / recolección", safety: "Información de seguridad del producto",
  physical: "Solo productos físicos; no son archivos descargables para imprimir.",
  adult: "Soy una persona adulta y estoy preparando esta solicitud.", adultNote: "Este recordatorio no verifica la edad ni la identidad.",
  prepare: "Preparar una solicitud", preparing: "Consultando los detalles actuales…", blocked: "No se puede solicitar esta selección ahora. Revisa la cantidad, la opción y la disponibilidad actual.",
  requestTitle: "Revisa tu solicitud", requestNote: "Abrir una aplicación de correo o mensajería no envía un mensaje ni confirma un pedido. Revisa y envía la solicitud tú mismo. La persona adulta que vende confirmará la disponibilidad, la entrega y el total final.",
  email: "Abrir correo para revisar", whatsapp: "Abrir WhatsApp para revisar", copy: "Copiar texto de la solicitud", copied: "Texto de la solicitud copiado.", copyFailed: "No se pudo copiar. Selecciona y copia manualmente el texto de abajo.",
  fallback: "Si la aplicación no abre, copia este texto y usa el contacto del negocio aprobado que aparece abajo.", contact: "Contacto del negocio", requestText: "Texto de tu solicitud",
  expiry: "Actualiza y prepara otra solicitud cuando estos detalles caduquen o cambien. No se envían solicitudes automáticamente.",
  requestOnly: "Esto es una consulta, no una compra. Los precios publicados no representan un total final con entrega incluida. El vendedor confirma los cargos e impuestos aplicables antes de aceptar el pedido.",
  howTitle: "Cómo funcionarán los pedidos", how1: "Elige un juguete físico y una opción disponible.", how2: "Una persona adulta revisa y envía la solicitud al contacto aprobado del negocio.", how3: "El vendedor confirma la disponibilidad, la entrega y el total final antes de aceptar el pedido.",
  privacyTitle: "Los juegos van por separado", privacy: "Las solicitudes no incluyen nombres de jugadores, avances ni creaciones. Esta página no recopila datos de pago.",
  policies: "Información del vendedor y de los pedidos", territory: "Dónde se aceptan pedidos", delivery: "Condiciones de entrega", returns: "Devoluciones", privacyPolicy: "Privacidad", information: "Información del vendedor",
  pendingPolicies: "El contacto del vendedor, las opciones de entrega y las condiciones de compra se publicarán antes de abrir las ventas.",
};
export const storeCopy = (language: StoreLanguage) => language === "es-MX" ? es : en;
