/** Bounded, authored activities. Spanish reviewed for meaning by the implementer, not a native-speaker certification. */
export type Band = 'gentle' | 'challenge'
export type Text = { en: string; 'es-MX': string }
const t = (en: string, es: string): Text => ({ en, 'es-MX': es })
export const missions = [
  {id:'supplies', title:t('1. Find the supplies','1. Encuentra los materiales'), objective:t('Count each object once and compare two groups.','Cuenta cada objeto una vez y compara dos grupos.'), example:t('Two bolts and one more bolt make three bolts.','Dos tornillos y un tornillo más son tres tornillos.'), alternative:t('Pair one object from each group. The group with extras has more.','Forma parejas con un objeto de cada grupo. El grupo con objetos sin pareja tiene más.')},
  {id:'battery',title:t('2. Charge the rescue robot','2. Carga el robot de rescate'),objective:t('Add what arrives; subtract what is used.','Suma lo que llega; resta lo que se usa.'),example:t('Four batteries plus two batteries make six.','Cuatro baterías más dos baterías son seis.'),alternative:t('Imagine a number line. Move right to add and left to subtract.','Imagina una recta numérica. Avanza a la derecha para sumar y a la izquierda para restar.')},
  {id:'signal',title:t('3. Repair the signal','3. Repara la señal'),objective:t('Find a repeating block or an equal number step.','Encuentra un bloque que se repite o un salto numérico constante.'),example:t('Red, blue, red, blue: the two-color block repeats. Red comes next.','Rojo, azul, rojo, azul: el bloque de dos colores se repite. Sigue rojo.'),alternative:t('Separate a repeating pattern into identical blocks. For numbers, compare neighboring terms.','Separa un patrón repetitivo en bloques iguales. Para los números, compara términos vecinos.')},
  {id:'route',title:t('4. Program the rescue','4. Programa el rescate'),objective:t('Put every instruction in an order that follows all the rules.','Ordena todas las instrucciones para cumplir todas las reglas.'),example:t('If A must happen before B, and B before C, choose A → B → C.','Si A debe ocurrir antes de B y B antes de C, elige A → B → C.'),alternative:t('Imagine cards in a row. Place a required earlier step to the left of its later step.','Imagina tarjetas en una fila. Coloca cada paso previo a la izquierda del paso que le sigue.')},
  {id:'debug',title:t('5. Fix the robot’s program','5. Corrige el programa del robot'),objective:t('Find the first incorrect instruction by checking one step at a time.','Encuentra la primera instrucción incorrecta revisando un paso a la vez.'),example:t('Required: A → B → C. Given: A → C → C. Step 2 is wrong: replace C with B.','Se necesita: A → B → C. Programa: A → C → C. El paso 2 está mal: cambia C por B.'),alternative:t('Compare two rows column by column. Stop at the first pair that differs.','Compara las dos filas columna por columna. Detente en el primer par diferente.')},
  {id:'rescue',title:t('6. Bring the robot home','6. Lleva el robot a casa'),objective:t('Use counting, addition, and subtraction in new rescue situations.','Usa el conteo, la suma y la resta en nuevas situaciones de rescate.'),example:t('There are two passengers. Three board. Now there are five passengers.','Hay dos pasajeros. Suben tres. Ahora hay cinco pasajeros.'),alternative:t('Draw one mark for each thing. Add marks for arrivals; cross out marks for departures.','Dibuja una marca por cada cosa. Agrega marcas cuando llegan; tacha marcas cuando se van.')},
] as const
export type LessonDiagram = { kind:'groups'; groups:number[]; operation?:'+'|'-' } | {kind:'tiles';rows:string[][]};
export interface LessonItem { diagram?:LessonDiagram; id:string; prompt:Text; visual:Text; answer:string; options:{id:string;label:Text}[]; hints:[Text,Text]; alternative:Text; feedback:Record<string,Text>; check:boolean; transfer:boolean }
type Body = Omit<LessonItem,'id'|'check'|'transfer'>
const numberItem = (prompt:Text,a:number,b:number,op:'+'|'-',options:number[]):Body => {
  const result=op==='+'?a+b:a-b
  return {diagram:{kind:'groups',groups:op==='+'?[a,b]:[a],operation:op==='+'?'+':undefined},prompt,visual:t(`${a} ${op} ${b} = ?`,`${a} ${op} ${b} = ?`),answer:String(result),options:options.map(n=>({id:String(n),label:t(String(n),String(n))})),
    hints:[t(op==='+'?'The group grows. Combine both amounts.':'Some leave. Start with the first amount and take away the second.',op==='+'?'El grupo crece. Junta las dos cantidades.':'Algunos se van. Empieza con la primera cantidad y quita la segunda.'),t(`Start at ${a}. Count ${b} steps ${op==='+'?'forward':'backward'}.`,`Empieza en ${a}. Cuenta ${b} pasos ${op==='+'?'hacia adelante':'hacia atrás'}.`)],
    alternative:t(op==='+'?`Draw ${a} dots in one box and ${b} in another. Count all the dots.`:`Draw ${a} dots. Cross out ${b}; count those still showing.`,op==='+'?`Dibuja ${a} puntos en una caja y ${b} en otra. Cuenta todos los puntos.`:`Dibuja ${a} puntos. Tacha ${b}; cuenta los que quedan.`),
    feedback:Object.fromEntries(options.map(n=>[String(n),n===result?t('Yes. You accounted for the whole change.','Sí. Tomaste en cuenta todo el cambio.'):t(`${n} is ${n<result?'too few':'too many'}. ${op==='+'?'Include both groups; count each object once.':'Remove only the amount used, then count what remains.'}`,`${n} es ${n<result?'muy poco':'demasiado'}. ${op==='+'?'Incluye ambos grupos; cuenta cada objeto una vez.':'Quita solo la cantidad usada y cuenta lo que queda.'}`)]))}
}
const count = (n:number, noun:Text, options:number[]):Body => ({
  diagram:{kind:'groups',groups:[n]},prompt:t(`How many ${noun.en} are ready?`,`¿Cuántos ${noun['es-MX']} están listos?`),visual:t(Array.from({length:n},()=> '●').join(' '),Array.from({length:n},()=> '●').join(' ')),answer:String(n),options:options.map(v=>({id:String(v),label:t(String(v),String(v))})),
  hints:[t('Point to each dot once. Say one number for each dot.','Señala cada punto una vez. Di un número por cada punto.'),t('Count from left to right. The last number tells how many.','Cuenta de izquierda a derecha. El último número indica cuántos hay.')],alternative:t('Make pairs of dots. Count two for each pair, then any dot left over.','Forma parejas de puntos. Cuenta dos por cada pareja y luego el punto que sobre.'),
  feedback:Object.fromEntries(options.map(v=>[String(v),v===n?t('Yes. Every dot was counted once.','Sí. Contaste cada punto una vez.'):t(v<n?'That count leaves some dots out. Check every dot.':'That count repeats a dot or adds one. Mark each dot only once.',v<n?'Ese conteo deja algunos puntos fuera. Revisa cada punto.':'Ese conteo repite o agrega un punto. Marca cada punto solo una vez.')]))
})
const compare = (left:number,right:number, context:Text):Body => ({diagram:{kind:'groups',groups:[left,right]},prompt:context,visual:t(`Left: ${left} • Right: ${right}`,`Izquierda: ${left} • Derecha: ${right}`),answer:left>right?'left':'right',options:[{id:'left',label:t('Left group','Grupo izquierdo')},{id:'right',label:t('Right group','Grupo derecho')},{id:'equal',label:t('Equal groups','Grupos iguales')}],hints:[t('Compare the amounts, not the length of the labels.','Compara las cantidades, no el largo de las etiquetas.'),t(`Pair ${Math.min(left,right)} from each side. Which side has extras?`,`Forma ${Math.min(left,right)} parejas, una de cada lado. ¿De qué lado sobran?`)],alternative:missions[0].alternative,feedback:{left:left>right?t('Yes. The left group has extras.','Sí. Sobran objetos a la izquierda.'):t('The left group runs out first when you make pairs. Try the other side.','El grupo izquierdo se acaba primero al formar parejas. Prueba el otro lado.'),right:right>left?t('Yes. The right group has extras.','Sí. Sobran objetos a la derecha.'):t('The right group runs out first when you make pairs. Try the other side.','El grupo derecho se acaba primero al formar parejas. Prueba el otro lado.'),equal:t('Equal groups would make pairs with no extras. These amounts differ.','Grupos iguales formarían parejas sin sobrantes. Estas cantidades son distintas.')}})
const names:Record<string,Text>={red:t('red','rojo'),blue:t('blue','azul'),circle:t('circle','círculo'),triangle:t('triangle','triángulo'),square:t('square','cuadrado')}
const pattern=(sequence:string[],answer:string,options:string[],rule:Text,context:Text):Body=>({diagram:{kind:'tiles',rows:[[...sequence,'?']]},prompt:context,visual:t(sequence.map(x=>names[x]?.en??x).join(' → ')+' → ?',sequence.map(x=>names[x]?.['es-MX']??x).join(' → ')+' → ?'),answer,options:options.map(id=>({id,label:names[id]??t(id,id)})),hints:[t('Look at how the pattern changes from one place to the next.','Observa cómo cambia el patrón de un lugar al siguiente.'),rule],alternative:names[answer]?t('Make a row of pretend cards for one complete repeating block. Lay an identical block beside it. Point to the card that fills the empty space.','Haz una fila de tarjetas imaginarias con un bloque completo del patrón. Pon un bloque idéntico junto a él. Señala la tarjeta que llena el espacio vacío.'):t('Picture these values as dots on a number line. Draw the same-sized jump between neighboring dots, then draw one more jump.','Imagina estos valores como puntos en una recta numérica. Dibuja saltos del mismo tamaño entre puntos vecinos y luego dibuja un salto más.'),feedback:Object.fromEntries(options.map(id=>[id,id===answer?t('Yes. That continues the stated pattern.','Sí. Eso continúa el patrón indicado.'):t(`Choosing ${names[id]?.en??id} breaks the rule. ${rule.en}`,`Elegir ${names[id]?.['es-MX']??id} rompe la regla. ${rule['es-MX']}`)]))})
const sequence=(answer:string,labels:Text[],options:string[],context:Text):Body=>{
  const rules=t(answer.split('').slice(0,-1).map((c,i)=>`${c.toUpperCase()} before ${answer[i+1].toUpperCase()}`).join('; '),answer.split('').slice(0,-1).map((c,i)=>`${c.toUpperCase()} antes de ${answer[i+1].toUpperCase()}`).join('; '))
  return {prompt:context,visual:t(labels.map((x,i)=>`${String.fromCharCode(65+i)}: ${x.en}`).join(' • ')+`. Rules: ${rules.en}.`,labels.map((x,i)=>`${String.fromCharCode(65+i)}: ${x['es-MX']}`).join(' • ')+`. Reglas: ${rules['es-MX']}.`),answer,options:options.map(id=>({id,label:t(id.toUpperCase().split('').join(' → '),id.toUpperCase().split('').join(' → '))})),hints:[t('Every earlier step must appear before the next required step.','Cada paso previo debe aparecer antes del siguiente paso requerido.'),t(`Begin with ${answer[0].toUpperCase()}. Then follow each before-rule.`,`Empieza con ${answer[0].toUpperCase()}. Después sigue cada regla de orden.`)],alternative:missions[3].alternative,feedback:Object.fromEntries(options.map(id=>{const wrong=answer.split('').slice(0,-1).find((c,i)=>id.indexOf(c)>id.indexOf(answer[i+1]));return [id,!wrong?t('Yes. Every order rule is satisfied.','Sí. Se cumplen todas las reglas de orden.'):t(`This puts ${wrong.toUpperCase()} too late. It must come before ${answer[answer.indexOf(wrong)+1].toUpperCase()}.`,`Esta opción pone ${wrong.toUpperCase()} muy tarde. Debe ir antes de ${answer[answer.indexOf(wrong)+1].toUpperCase()}.`)]}))}
}
const debug=(required:string[],given:string[],context:Text):Body=>{
  const index=required.findIndex((x,i)=>x!==given[i]); const answer=String(index+1)
  return {diagram:{kind:'tiles',rows:[required,given]},prompt:context,visual:t(`Required: ${required.join(' → ')}. Program: ${given.join(' → ')}.`,`Se necesita: ${required.join(' → ')}. Programa: ${given.join(' → ')}.`),answer,options:required.map((_,i)=>({id:String(i+1),label:t(`Step ${i+1}`,`Paso ${i+1}`)})),hints:[t('Compare the first instruction in each row, then the second, and so on.','Compara la primera instrucción de cada fila, luego la segunda, y así sucesivamente.'),t('A step is correct only if its symbol matches the required symbol at the same position.','Un paso es correcto solo si su símbolo coincide con el símbolo requerido en esa posición.')],alternative:missions[4].alternative,feedback:Object.fromEntries(required.map((_,i)=>[String(i+1),i===index?t(`Yes. Replace ${given[i]} with ${required[i]} at this step.`,`Sí. Cambia ${given[i]} por ${required[i]} en este paso.`):t(`Step ${i+1} already matches (${required[i]}). Check the other positions.`,`El paso ${i+1} ya coincide (${required[i]}). Revisa las otras posiciones.`)]))}
}
const data: Body[][][] = [
  [
    [count(3,t('bolts','tornillos'),[2,3,4]),compare(6,4,t('Which shelf holds more batteries?','¿Qué estante tiene más baterías?')),count(5,t('gears','engranes'),[4,6,5]),compare(3,7,t('The robot needs the basket with more apples. Which basket?','El robot necesita la canasta con más manzanas. ¿Cuál elige?'))],
    [count(12,t('bolts','tornillos'),[11,12,13]),compare(14,17,t('Which shelf holds more batteries?','¿Qué estante tiene más baterías?')),count(15,t('gears','engranes'),[14,16,15]),compare(19,16,t('Choose the rescue boat with more empty seats.','Elige la lancha de rescate con más asientos vacíos.'))],
  ],
  [
    [numberItem(t('The robot has 2 batteries and receives 3. How many now?','El robot tiene 2 baterías y recibe 3. ¿Cuántas tiene ahora?'),2,3,'+',[4,5,6]),numberItem(t('There are 7 bolts. Use 4. How many remain?','Hay 7 tornillos. Usa 4. ¿Cuántos quedan?'),7,4,'-',[3,4,11]),numberItem(t('Join 4 red wires and 3 blue wires. How many wires?','Junta 4 cables rojos y 3 azules. ¿Cuántos cables hay?'),4,3,'+',[1,6,7]),numberItem(t('Six passengers are aboard. Two get off. How many stay?','Hay 6 pasajeros a bordo. Bajan 2. ¿Cuántos quedan?'),6,2,'-',[2,4,8])],
    [numberItem(t('The robot has 8 batteries and receives 7. How many now?','El robot tiene 8 baterías y recibe 7. ¿Cuántas tiene ahora?'),8,7,'+',[14,15,16]),numberItem(t('There are 16 bolts. Use 7. How many remain?','Hay 16 tornillos. Usa 7. ¿Cuántos quedan?'),16,7,'-',[8,9,23]),numberItem(t('Join 9 red wires and 8 blue wires. How many wires?','Junta 9 cables rojos y 8 azules. ¿Cuántos cables hay?'),9,8,'+',[1,16,17]),numberItem(t('Thirteen passengers are aboard. Five get off. How many stay?','Hay 13 pasajeros a bordo. Bajan 5. ¿Cuántos quedan?'),13,5,'-',[7,8,18])],
  ],
  [
    [pattern(['red','blue','red'],'blue',['red','blue','circle'],t('Repeat red, blue.','Repite rojo, azul.'),t('The beacon repeats two colors. What comes next?','La baliza repite dos colores. ¿Cuál sigue?')),pattern(['circle','triangle','circle','triangle'],'circle',['triangle','square','circle'],t('Repeat circle, triangle.','Repite círculo, triángulo.'),t('The panel repeats two shapes. Which comes next?','El panel repite dos figuras. ¿Cuál sigue?')),pattern(['red','red','blue','red','red','blue'],'red',['blue','red','square'],t('Repeat red, red, blue.','Repite rojo, rojo, azul.'),t('Continue the repeating three-color block.','Continúa el bloque repetitivo de tres colores.')),pattern(['triangle','square','circle','triangle','square','circle'],'triangle',['circle','square','triangle'],t('Repeat triangle, square, circle.','Repite triángulo, cuadrado, círculo.'),t('Floor tiles repeat this three-shape block. Which tile is next?','Las losetas repiten este bloque de tres figuras. ¿Cuál sigue?'))],
    [pattern(['3','6','9','12'],'15',['14','15','16'],t('Add 3 each time.','Suma 3 cada vez.'),t('The signal increases by the same amount each time. What comes next?','La señal aumenta lo mismo cada vez. ¿Qué sigue?')),pattern(['6','10','14'],'18',['16','17','18'],t('Add 4 each time.','Suma 4 cada vez.'),t('Battery readings rise by an equal step. Continue.','Las lecturas de la batería aumentan con un salto constante. Continúa.')),pattern(['1','6','11','16'],'21',['20','21','22'],t('Add 5 each time.','Suma 5 cada vez.'),t('Continue these equally spaced channel numbers.','Continúa estos números de canal con separación constante.')),pattern(['8','11','14','17'],'20',['19','20','21'],t('Add 3 each time.','Suma 3 cada vez.'),t('Trail signs use an equal number step. What number goes on the next sign?','Los letreros del sendero usan un salto numérico constante. ¿Qué número lleva el siguiente?'))],
  ],
  [
    [sequence('abc',[t('find key','buscar llave'),t('unlock','abrir cerradura'),t('open door','abrir puerta')],['bac','abc','acb'],t('Choose the order that opens the rescue door.','Elige el orden que abre la puerta de rescate.')),sequence('bac',[t('load supplies','cargar materiales'),t('park cart','estacionar carrito'),t('deliver','entregar')],['abc','bca','bac'],t('Choose a delivery plan that follows the rules.','Elige un plan de entrega que siga las reglas.')),sequence('cab',[t('attach cable','conectar cable'),t('charge','cargar batería'),t('find charger','buscar cargador')],['cab','acb','cba'],t('Put the charging instructions in order.','Ordena las instrucciones para cargar la batería.')),sequence('acb',[t('wash cup','lavar taza'),t('serve water','servir agua'),t('fill cup','llenar taza')],['abc','acb','cab'],t('Apply the ordering rules at the water station.','Aplica las reglas de orden en la estación de agua.'))],
    [sequence('abcd',[t('find key','buscar llave'),t('unlock','abrir cerradura'),t('open door','abrir puerta'),t('enter','entrar')],['abdc','bacd','abcd'],t('Choose the four-step door program.','Elige el programa de cuatro pasos para la puerta.')),sequence('bcad',[t('load supplies','cargar materiales'),t('park cart','estacionar carrito'),t('open cart','abrir carrito'),t('deliver','entregar')],['bacd','bcad','cbad'],t('Choose a four-step delivery plan.','Elige un plan de entrega de cuatro pasos.')),sequence('cadb',[t('attach cable','conectar cable'),t('disconnect','desconectar'),t('find charger','buscar cargador'),t('charge','cargar batería')],['cdab','cabd','cadb'],t('Follow every charging rule.','Sigue todas las reglas de carga.')),sequence('bdac',[t('fill cup','llenar taza'),t('find cup','buscar taza'),t('serve water','servir agua'),t('wash cup','lavar taza')],['badc','bdac','dbac'],t('Use the ordering rules at the water station.','Usa las reglas de orden en la estación de agua.'))],
  ],
  [
    [debug(['A','B','C'],['A','C','C'],t('Door commands must match the required row. Which step needs repair?','Los comandos de la puerta deben coincidir con la fila requerida. ¿Qué paso se corrige?')),debug(['B','A','C'],['A','A','C'],t('Find the incorrect cart command.','Encuentra el comando incorrecto del carrito.')),debug(['C','A','B'],['C','A','A'],t('Which charging command differs from its required position?','¿Qué comando de carga no coincide con su posición requerida?')),debug(['○','△','□'],['○','□','□'],t('A printer should make the required shape row. Which print step is wrong?','Una impresora debe hacer la fila de figuras requerida. ¿Qué paso de impresión está mal?'))],
    [debug(['A','B','C','D'],['A','B','D','D'],t('Which door command needs replacement?','¿Qué comando de la puerta se debe cambiar?')),debug(['B','C','A','D'],['B','C','A','A'],t('Find the incorrect command in the delivery program.','Encuentra el comando incorrecto del programa de entrega.')),debug(['C','A','D','B'],['C','D','D','B'],t('Compare the charging rows. Which step is incorrect?','Compara las filas de carga. ¿Qué paso está mal?')),debug(['△','○','□','◇'],['○','○','□','◇'],t('The mural printer must match the required shape row. Which step needs repair?','La impresora del mural debe seguir la fila de figuras requerida. ¿Qué paso se corrige?'))],
  ],
  [
    [numberItem(t('Four robots wait at the dock. Two arrive. How many are there?','Esperan 4 robots en el muelle. Llegan 2. ¿Cuántos hay?'),4,2,'+',[2,5,6]),numberItem(t('The boat has 8 life jackets. Give out 5. How many remain?','La lancha tiene 8 chalecos. Reparte 5. ¿Cuántos quedan?'),8,5,'-',[3,4,13]),numberItem(t('Five robots are rescued from one dock and 3 from another. How many in all?','Rescatan 5 robots de un muelle y 3 de otro. ¿Cuántos en total?'),5,3,'+',[2,7,8]),numberItem(t('At home there are 9 plant pots. Water 4. How many still need water?','En casa hay 9 macetas. Riegas 4. ¿Cuántas faltan por regar?'),9,4,'-',[4,5,13])],
    [numberItem(t('Twelve robots wait at the dock. Seven arrive. How many are there?','Esperan 12 robots en el muelle. Llegan 7. ¿Cuántos hay?'),12,7,'+',[5,18,19]),numberItem(t('The boat has 17 life jackets. Give out 9. How many remain?','La lancha tiene 17 chalecos. Reparte 9. ¿Cuántos quedan?'),17,9,'-',[7,8,26]),numberItem(t('Fourteen robots are rescued from one dock and 9 from another. How many in all?','Rescatan 14 robots de un muelle y 9 de otro. ¿Cuántos en total?'),14,9,'+',[5,22,23]),numberItem(t('At home there are 20 plant pots. Water 8. How many still need water?','En casa hay 20 macetas. Riegas 8. ¿Cuántas faltan por regar?'),20,8,'-',[11,12,28])],
  ],
]
export function lessonItem(mission:number,position:number,band:Band):LessonItem {
  if(!Number.isInteger(mission)||!Number.isInteger(position)||mission<0||mission>=missions.length||position<0||position>=4||!(band==='gentle'||band==='challenge')) throw new RangeError('Unknown lesson item')
  return {...data[mission][band==='gentle'?0:1][position],id:`${missions[mission].id}:${band}:${position}`,check:position>=2,transfer:position===3}
}
const challengeExamples:Text[]=[t('A group of 13 and a group of 11 make 11 pairs. Two are left in the first group, so 13 is greater.','Un grupo de 13 y otro de 11 forman 11 parejas. Sobran dos en el primero, así que 13 es mayor.'),t('To add 7 and 6, add 3 to reach 10, then the remaining 3. The result is 13.','Para sumar 7 y 6, suma 3 para llegar a 10 y luego los otros 3. El resultado es 13.'),t('2, 6, 10, 14 increases by 4 each time. Add 4 to 14 to get 18.','2, 6, 10, 14 aumenta de 4 en 4. Suma 4 a 14 para obtener 18.'),t('Rules: D before A, A before B, B before C. Start with D, then A, B, C.','Reglas: D antes de A, A antes de B, B antes de C. Empieza con D, luego A, B, C.'),t('Required: D → A → B → C. Program: D → A → A → C. Steps 1 and 2 match. Step 3 needs B instead of A.','Se necesita: D → A → B → C. Programa: D → A → A → C. Los pasos 1 y 2 coinciden. El paso 3 necesita B en lugar de A.'),t('There are 18 seats and 6 are occupied. Draw 18 marks and cross out 6. Twelve seats remain free.','Hay 18 asientos y 6 están ocupados. Dibuja 18 marcas y tacha 6. Quedan 12 asientos libres.')]
export function workedExample(mission:number,band:Band):Text {
  if(!missions[mission]) throw new RangeError('Unknown mission')
  return band==='challenge'?challengeExamples[mission]:missions[mission].example
}
