import {priceFor,magicPrice} from './save';
export type Copy={en:string;'es-MX':string};
export const copy=(en:string,es:string):Copy=>({en,'es-MX':es});
export const GROUPS=[copy('Frames','Chasis'),copy('Wheels','Llantas'),copy('Motors','Motores'),copy('Suspension','Suspensión'),copy('Drive & balance','Tracción y equilibrio'),copy('Protection','Protección'),copy('Adventure','Aventura'),copy('Body kits','Carrocerías'),copy('Exhaust & wings','Escapes y alerones'),copy('Finishing touches','Detalles')];
const rows=[
'Tiny Buggy Frame|Chasis de buggy pequeño','Crawler Frame|Chasis trepador','Monster Hauler Frame|Chasis de carga monstruosa','Sky Rider Frame|Chasis jinete del cielo','Rhino Ram Frame|Chasis rinoceronte','Spider Stretch Frame|Chasis araña','Dune Skipper Frame|Chasis saltadunas','Frog Jumper Frame|Chasis rana saltarina','Beetle Belly Frame|Chasis escarabajo','Twin-Deck Rover Frame|Chasis explorador de dos pisos',
'Grippy Jungle Tires|Llantas de selva','Lava Crusher Wheels|Ruedas de lava','Ice Drift Wheels|Ruedas de hielo','Turbo Spark Wheels|Ruedas turbo chispa','Bone Roller Wheels|Ruedas de fósil','Swamp Paddle Tires|Llantas de pantano','Moon Balloon Tires|Llantas globo lunar','Sand Skimmer Wheels|Ruedas de arena','Rock Claw Wheels|Ruedas garra de roca','Spring Rim Wheels|Ruedas de resorte',
'Blaze Core Engine|Motor núcleo de fuego','Thunder Coil Engine|Motor bobina de trueno','Crystal Pulse Engine|Motor pulso de cristal','Mud Chugger Engine|Motor todolodo','Storm Jet Engine|Motor turbina de tormenta','Firefly Mini Motor|Minimotor luciérnaga','Rhino Torque Engine|Motor fuerza rinoceronte','Panther Cruise Engine|Motor pantera','Tortoise Trail Engine|Motor tortuga','Twin Heart Engine|Motor corazón doble',
'Spring Hopper Suspension|Suspensión saltarina','Rock Stomper Suspension|Suspensión pisarrocas','Cloud Glide Suspension|Suspensión nube','Spider Leg Suspension|Suspensión patas de araña','Frog Squat Suspension|Suspensión rana','Beetle Flex Suspension|Suspensión flexible de escarabajo','Long Reach Suspension|Suspensión de largo alcance','Stomp Stop Dampers|Amortiguadores antirrebote','Dual-Axle Rocker|Balancín de doble eje','Swingtail Rear Axle|Eje trasero oscilante',
'Gecko Climb Gearbox|Caja de cambios gecko','Cheetah Sprint Gearbox|Caja de cambios guepardo','Switchback Two-Speed Gearbox|Caja de dos velocidades','Twin-Axle Drive Module|Tracción de doble eje','Six-Wheel Drive Module|Tracción de seis ruedas','Hill Hold Brake|Freno para pendientes','Smooth Stop Brake|Freno suave','Belly Ballast Block|Contrapeso inferior','Sliding Engine Rail|Riel deslizante del motor','Wheelbase Extender|Extensor de distancia entre ejes',
'Rhino Horn Bumper|Defensa cuerno de rinoceronte','Shark Jaw Grille|Parrilla mandíbula de tiburón','Dino Skull Bumper|Defensa cráneo de dinosaurio','Beetle Shield Plow|Pala escudo de escarabajo','Turtle Shell Roll Cage|Jaula caparazón de tortuga','Manta Glide Skid Plate|Placa deslizante mantarraya','Spring Nose Bumper|Defensa nariz de resorte','Tailwheel Stabilizer|Estabilizador con rueda trasera','Root Lifter Ramp Nose|Nariz rampa levantadora','Crocodile Belly Guard|Protector inferior cocodrilo',
'Gecko Grapple Winch|Cabrestante gecko','Beaver Bridge Rack|Puente plegable castor','Bubble Float Pontoons|Flotadores burbuja','Otter Paddle Drive|Propulsor de paletas nutria','Falcon Folding Glider|Planeador halcón','Firefly Searchlight|Reflector luciérnaga','Honeybee Cargo Tray|Bandeja de carga abeja','Turtle Tow Hitch|Enganche tortuga','Rolling Rescue Trailer|Remolque de rescate','Kangaroo Recovery Arm|Brazo de recuperación canguro',
'Panther Prowl Hood|Cofre pantera','Dragon Scale Body Kit|Carrocería escamas de dragón','Shark Stream Cab|Cabina tiburón','Dino Back Armor|Armadura dorsal de dinosaurio','Beetle Shell Canopy|Techo caparazón de escarabajo','Rhino Ridge Fenders|Salpicaderas rinoceronte','Crystal Cave Cabin|Cabina cueva de cristal','Moon Buggy Bubble Roof|Techo burbuja lunar','Jungle Vine Side Panels|Paneles enredadera','Volcano Vent Hood|Cofre volcánico',
'Dragon Wing Spoiler|Alerón alas de dragón','Scorpion Tail Exhaust|Escape cola de escorpión','Phoenix Flame Pipes|Escapes llama de fénix','Shark Fin Spoiler|Alerón aleta de tiburón','Batwing Spoiler|Alerón alas de murciélago','Crystal Shard Spoiler|Alerón de cristal','Octopus Twin Pipes|Escapes gemelos pulpo','Thunderbolt Exhaust|Escape relámpago','Cloud Puff Tailpipes|Escapes nube','Meteor Ring Exhaust|Escape anillo de meteoro',
'Bug Eye Headlights|Faros ojos de insecto','Crystal Prism Headlights|Faros prisma de cristal','Moon Halo Light Bar|Barra de luz lunar','Dino Horn Roof Lights|Luces cuernos de dinosaurio','Deep Cave Spotlight Rack|Reflectores de cueva','Phoenix Crest Topper|Adorno cresta de fénix','Monster Jaw Wheel Guards|Guardas mandíbula de monstruo','Rocket Snail Roof Pet|Caracol cohete de techo','Hologram Monster Badge|Insignia holográfica','Golden Gear Trophy Topper|Trofeo engrane dorado'];
const hints=[
'Light and short; bouncy on rough ground.|Ligero y corto; rebota en terreno difícil.','Long and low; can scrape on sharp crests.|Largo y bajo; puede rozar las crestas.','Wide and sturdy; carries extra weight.|Ancho y resistente; pesa más.','Lightweight launch frame; more delicate.|Chasis ligero para saltos; más delicado.','Heavy reinforced nose; balance the motor.|Nariz reforzada y pesada; equilibra el motor.','Wide wheel mounts; takes more room.|Soportes anchos; ocupa más espacio.','Curved underbody; less scraping in sand.|Parte inferior curva; roza menos la arena.','Raised center; extra wheel clearance.|Centro elevado; más espacio para las ruedas.','Compact and low; stays balanced.|Compacto y bajo; mantiene el equilibrio.','Tall mounting deck; watch your balance.|Plataforma alta; cuida el equilibrio.',
'Mud grip with some rolling resistance.|Agarre en lodo con algo de resistencia.','Huge and heavy; clear bigger rocks.|Grandes y pesadas; pasan rocas mayores.','Slippery tires for drifting challenges.|Llantas resbalosas para retos de derrape.','Quick on smooth roads; small over rocks.|Rápidas en caminos lisos; pequeñas para rocas.','Balanced tread for mixed terrain.|Dibujo equilibrado para terreno variado.','Paddle treads resist deep mud.|Paletas que avanzan por lodo profundo.','Soft, huge and very bouncy.|Suaves, enormes y muy rebotadoras.','Wide footprint for sandy routes.|Llantas anchas para rutas de arena.','Strong grip with a rougher ride.|Gran agarre con un viaje más brusco.','Flexible spokes absorb bumps and rebound.|Rayos flexibles que absorben golpes y rebotan.',
'Fast acceleration; adds engine weight.|Acelera rápido; agrega peso.','Quick pedal response; control the power.|Respuesta rápida; controla la potencia.','Gentle acceleration for careful driving.|Aceleración suave para conducir con cuidado.','Pulls through slow, muddy sections.|Avanza en tramos lentos y lodosos.','High top speed; slower off the line.|Alta velocidad máxima; arranque más lento.','Light starter motor; best with light cars.|Motor inicial ligero; ideal para autos ligeros.','Heavy motor for steep hills.|Motor pesado para pendientes fuertes.','Balanced power for different routes.|Potencia equilibrada para distintas rutas.','Slow and steady for precise driving.|Lento y estable para conducir con precisión.','Powerful twin chambers; very heavy.|Dos cámaras potentes; muy pesado.',
'Visible spring rebound on landings.|Rebote visible al aterrizar.','Stiff shocks support heavy cars.|Amortiguadores firmes para autos pesados.','Soft landing springs; more sway.|Resortes suaves; más movimiento.','Long arms follow uneven ground.|Brazos largos para terreno irregular.','Deep travel; heavy cars can bottom out.|Mucho recorrido; autos pesados pueden rozar.','Compact, firm leaf springs.|Resortes compactos y firmes.','Raises the body and center of balance.|Eleva la carrocería y el centro de equilibrio.','Strong damping reduces repeated bouncing.|Amortiguación que reduce rebotes repetidos.','Adds a middle wheel pair for six-wheel builds.|Agrega un par central para seis ruedas.','Rear suspension has extra travel.|Suspensión trasera con recorrido adicional.',
'More climbing force, lower top speed.|Más fuerza para subir, menos velocidad máxima.','Higher top speed, less climbing force.|Más velocidad máxima, menos fuerza para subir.','Automatic low gear on slopes, high on flats.|Cambio automático: baja en pendientes, alta en rectas.','Both axles pull when touching the ground.|Ambos ejes impulsan al tocar el suelo.','Adds and powers a third wheel pair.|Agrega y mueve un tercer par de ruedas.','Holds on a slope when you release the pedal.|Sostiene el auto al soltar el acelerador.','Brakes more gently; allow more stopping room.|Frena suavemente; necesita más distancia.','Lowers balance but adds weight.|Baja el centro de equilibrio, pero pesa más.','Makes engine position changes more pronounced.|Amplía el efecto de mover el motor.','Extends your chosen wheel spacing.|Amplía la distancia elegida entre ruedas.',
'Reinforced front; adds nose weight.|Frente reforzado; agrega peso adelante.','Curved front slides over small obstacles.|Frente curvo que desliza sobre obstáculos pequeños.','High-mounted protection keeps nose clearance.|Protección elevada que deja espacio abajo.','Broad protective nose; can catch steep crests.|Nariz ancha y protectora; puede rozar crestas.','Rounded roof makes recovering easier.|Techo redondo que facilita recuperarse.','Smooth plate reduces underbody drag.|Placa lisa que reduce el roce inferior.','Softens impacts but can bounce backward.|Suaviza impactos, pero puede rebotar hacia atrás.','Catches some backward tips.|Ayuda a detener algunas volcadas hacia atrás.','Curved ramp nose helps approach ledges.|Nariz curva que ayuda a subir bordes.','Thick underside protection adds weight.|Protección inferior gruesa que agrega peso.',
'Tap Tool near a marked post to pull forward.|Toca Herramienta cerca de un poste para avanzar.','Tap Tool at a water gap to lay a bridge.|Toca Herramienta ante el agua para poner un puente.','Float across water; land speed is lower.|Flota en agua; menor velocidad en tierra.','Paddle across water; pair with floats.|Avanza con paletas; combina con flotadores.','Automatically slows descent after a jump.|Reduce automáticamente la caída tras un salto.','Lights a wider beam in Crystal Cave.|Ilumina un haz amplio en la Cueva de Cristal.','Carry a parcel; hard crashes can drop it.|Lleva un paquete; los golpes fuertes lo tiran.','Required to connect the rescue trailer.|Necesario para conectar el remolque.','Tow a little carriage when a hitch is fitted.|Lleva un carrito al instalar un enganche.','Tap Tool to push a tipped car upright.|Toca Herramienta para levantar un auto volcado.'
];
export const PALETTES=[['#ff7b2d','#ffe080'],['#36c8bd','#c1ff9e'],['#9b7bff','#73e5ff'],['#fa607b','#ffe39b'],['#4da9ff','#e4f7ff'],['#d3b479','#aef09c']];
export const PARTS=rows.map((row,i)=>{const [en,es]=row.split('|'),hint=hints[i]?.split('|');return {id:i+1,group:Math.floor(i/10),name:copy(en,es),description:hint?copy(hint[0],hint[1]):copy('Cosmetic: changes the look, not driving performance.','Cosmético: cambia la apariencia, no el manejo.'),price:priceFor(i+1),color:PALETTES[i%6][0],accent:PALETTES[i%6][1],functional:i<70};});
export const MAGIC=[
['Rainbow Ribbon','Cinta arcoíris','A bridge you can ride across.','Un puente por el que puedes pasar.'],['Cloud Cushion','Cojín de nube','Bounces your unicorn upward.','Impulsa tu unicornio hacia arriba.'],['Growing Vine','Enredadera','Hold jump beside it to climb.','Mantén Saltar junto a ella para subir.'],['Rainbow Slide','Resbaladilla arcoíris','A sloping path with a speed boost.','Un camino inclinado que te impulsa.'],['Flower Elevator','Elevador de flor','Ride a flower moving up and down.','Viaja en una flor que sube y baja.'],['Cloud Boat','Barco de nube','A platform that sails sideways.','Una plataforma que se mueve de lado.'],['Mushroom Spring','Resorte de hongo','A higher bounce for tall discoveries.','Un salto más alto para descubrir lugares.'],['Crystal Steps','Escalones de cristal','A small staircase to climb.','Una pequeña escalera para subir.'],['Garden Treehouse','Casita del jardín','A tall platform and a safe resting place.','Una plataforma alta para descansar.'],['Moon Gate','Portal lunar','Links to the next placed moon gate.','Conecta con el siguiente portal colocado.'],['Lantern Blossom','Flor linterna','Lights the moon garden around your unicorn.','Ilumina el jardín lunar a tu alrededor.'],['Rainbow Fountain','Fuente arcoíris','A gentle fountain lifts you upward.','Una fuente suave que te eleva.']
].map(([en,es,de,ds],i)=>({id:i+1,name:copy(en,es),description:copy(de,ds),price:magicPrice(i+1)}));
export const ROUTES=[copy('Meadow Rally','Rally del prado'),copy('Dune Dash','Carrera de dunas'),copy('Crystal Cave','Cueva de cristal')];
export const ISLANDS=[copy('Cloud Kitten Garden','Jardín de gatitos nube'),copy('Dragon Blossom Valley','Valle de flores dragón'),copy('Moonlight Fox Trail','Sendero del zorro lunar')];
