import {useEffect,useRef,useState} from 'react';
import type {Language} from '../types';
import {GROUPS,PARTS,PALETTES,ROUTES} from './catalog';
import {buyPart,equipPart,finishDrive,normalizeBuild,type Build,type Drive} from './save';
import {carStats,has,makeDrive} from './carPhysics';
import {box,drawCar,partArt} from './carArt';
import {useReducedMotion} from './controls';
import {useGameSave} from './useGameSave';
import './creative-games.css';
import './truck-upgrade.css';
import TruckDriveStage from './TruckDriveStage';
import {findGarageParts,startGarageAttempt,GARAGE_PROJECTS,type PartFilter} from './garageExperience';
const clone=<T,>(v:T):T=>structuredClone(v);
function PartPicture({id}:{id:number}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current?.getContext('2d');if(!c)return;c.clearRect(0,0,180,106);partArt(c,id,90,57,.86);},[id]);return <canvas ref={ref} width="180" height="106" aria-hidden="true"/>;}
export function GaragePicture({build}:{build:Build}){const ref=useRef<HTMLCanvasElement>(null),reduced=useReducedMotion();useEffect(()=>{const el=ref.current;if(!el)return;const c=el.getContext('2d');if(!c)return;let frame=0;const draw=(time:number)=>{const w=el.clientWidth||600,h=el.clientHeight||300,d=Math.min(2,window.devicePixelRatio||1);if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d);}c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const glow=c.createRadialGradient(w*.5,h*.45,15,w*.5,h*.6,w*.6);glow.addColorStop(0,'#365063');glow.addColorStop(1,'#111e32');c.fillStyle=glow;c.fillRect(0,0,w,h);c.strokeStyle='#b6e8ff0a';c.lineWidth=1;for(let x=0;x<w;x+=36){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=36){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}const scale=Math.min(w/330,h/200),r=makeDrive(build);r.x=0;r.y=0;r.t=reduced.current?0:time/1000;c.save();c.translate(w*.5,h*.59);c.scale(scale,scale);c.fillStyle='#07132288';c.beginPath();c.ellipse(0,67,123,15,0,0,Math.PI*2);c.fill();box(c,-140,80,280,9,'#7cc2d5',3,'#234354',1);drawCar(c,r,true);c.restore();frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame);},[JSON.stringify(build)]);return <canvas ref={ref} className="cg-garage-art" role="img" aria-label={build.name}/>;}
export default function MonsterGarage({close}:{close:()=>void}){
 const {profile,games,setGarage,saveState}=useGameSave(),g=games.garage,lang=profile.language,es=lang==='es-MX';
 const [group,setGroup]=useState(1),[selected,setSelected]=useState(()=>g.build.parts[1]),[extra,setExtra]=useState(false),[route,setRoute]=useState(0),[drive,setDrive]=useState<Drive|null>(null),[scene,setScene]=useState(0),[message,setMessage]=useState('');
 const token=useRef(0),launching=useRef(false);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState<PartFilter>('all');
 useEffect(()=>{launching.current=false;},[scene]);
 const latest=useRef<Drive|null>(null),part=PARTS[selected-1],owned=g.owned.includes(selected),target=PARTS[g.target-1];
 const previewParts=[...g.build.parts];if(part)previewParts[group===4&&extra?10:group===6&&extra?11:part.group]=selected;
 const preview=normalizeBuild({...g.build,parts:previewParts},PARTS.map(p=>p.id)),stats=carStats(preview);
 const edit=(patch:Partial<Build>)=>setGarage(current=>({...current,build:normalizeBuild({...current.build,...patch},current.owned)}));
 const showDrive=(r:Drive)=>{token.current++;latest.current=r;setDrive(r);setScene(token.current);setMessage('');window.scrollTo({top:0,behavior:'auto'});};
 const begin=(practice=false,trial=false,previous:Drive|null=null)=>{
  if(launching.current)return;launching.current=true;
  const options={build:previous?.build??(trial?preview:g.build),track:previous?.track??route,practice,trial,previous};
  const prepared=startGarageAttempt(g,options);
  if(!trial)setGarage(current=>startGarageAttempt(current,options).garage);
  showDrive(prepared.run);
 };
 const bank=(r:Drive|null=latest.current)=>{if(r&&r.id>0)setGarage(current=>finishDrive(current,r));token.current++;setDrive(null);latest.current=null;};
 const checkpoint=(r:Drive,origin:number)=>{if(token.current!==origin)return;latest.current=r;if(r.id>0)setGarage(current=>r.id===current.sequence&&r.id>current.paidThrough?{...current,resume:r}:current);};
 const back=()=>{bank();close();};
 return <section className="cg-shell cg-garage" data-testid="monster-garage"><header className="cg-topbar"><button type="button" onClick={back}>← {es?'Sala de juegos':'Arcade'}</button><span className="cg-wordmark">NICO’S <b>MONSTER GARAGE</b></span><div className="cg-wallet"><span aria-hidden="true">⬡</span><strong data-testid="garage-bolts">{g.bolts}</strong><small>{es?'tornillos':'bolts'}</small></div></header>
 {saveState.status==='error'&&<p role="alert" className="cg-save-error">{es?'No se pudo guardar en este navegador. No cierres antes de respaldar tu perfil.':'This browser could not save. Back up your profile before closing.'}</p>}
 {drive?<><TruckDriveStage key={scene} initial={drive} language={lang} best={g.best[drive.track]} onSample={r=>{if(token.current===scene)latest.current=r;}} onCheckpoint={r=>checkpoint(r,scene)} onEnd={r=>{if(token.current===scene&&r.id>0)setGarage(current=>finishDrive(current,r));}} onReturn={r=>bank(r)} onRetry={r=>begin(r.practice,r.id===0,r)}/>{g.last&&drive.id>0&&g.paidThrough===drive.id&&<div className="cg-receipt" role="status">{es?'Ganaste':'Earned'} <strong>{g.last.bolts+g.last.bonus+g.last.challenge} {es?'tornillos':'bolts'}</strong> · {g.last.bolts} {es?'por distancia':'distance'} + {g.last.bonus} {es?'por récord':'personal best'} + {g.last.challenge} {es?'por retos':'challenges'}</div>}</>:<>
 <div className="cg-intro"><div><span className="cg-eyebrow">{es?'100 PIEZAS · TU IMAGINACIÓN':'100 PARTS · YOUR IMAGINATION'}</span><h2>{es?'Construye algo':'Build something'}<em>{es?'extraordinario.':'extraordinary.'}</em></h2><p>{es?'Arma tu auto, salta las rampas y descubre qué tan lejos llega. Las reparaciones siempre son gratis.':'Build your car, launch off ramps, and see how far it goes. Repairs are always free.'}</p></div><div className="cg-collection-count"><strong>{g.owned.length}<span>/100</span></strong><small>{es?'piezas tuyas para siempre':'parts yours to keep'}</small></div></div>
 {g.resume&&<div className="cg-resume"><span>{es?'Tienes un recorrido guardado':'You have a saved drive'} · {Math.floor(g.resume.distance)} m</span><button type="button" className="cg-primary" onClick={()=>{showDrive(clone(g.resume!));}}>{es?'Continuar recorrido':'Resume drive'}</button><button type="button" onClick={()=>setGarage(current=>current.resume?finishDrive(current,current.resume):current)}>{es?'Cobrar y reconstruir':'Bank & rebuild'}</button></div>}
 <div className="cg-workbench"><div className="cg-preview"><GaragePicture build={preview}/><div className="cg-preview-caption"><span>{selected!==g.build.parts[part.group]?(owned?(es?'Vista previa de pieza':'Part preview'):(es?'Vista previa · aún no es tuya':'Preview · not owned yet')):(es?'TU CREACIÓN':'YOUR CREATION')}</span><strong>{g.build.name}</strong></div><div className="cg-paint-row">{PALETTES.map(([color],i)=><button key={color} type="button" className="cg-swatch" style={{background:color}} aria-label={`${es?'Pintura':'Paint'} ${i+1}`} aria-pressed={g.build.paint===i} onClick={()=>edit({paint:i})}/>)}<label>{es?'Piloto':'Driver'}<select value={g.build.driver} onChange={e=>edit({driver:Number(e.target.value)})}>{['Moss','Nova','Aqua','Ember'].map((name,i)=><option key={name} value={i}>{name}</option>)}</select></label></div>{!g.build.parts.includes(selected)&&<div className="cg-preview-warning"><span>{es?'Vista previa: instala la pieza para usarla. El botón de manejar usa tu auto guardado.':'Preview: fit this part to use it. Driving uses your saved car.'}</span><button type="button" onClick={()=>{setGroup(1);setSelected(g.build.parts[1]);}}>{es?'Ver mi auto':'Show my car'}</button></div>}</div>
 <aside className="cg-build-panel"><label>{es?'Nombre del auto':'Car name'}<input maxLength={26} value={g.build.name} onChange={e=>edit({name:e.target.value})}/></label><div className="cg-meter"><span>{es?'Potencia':'Power'}</span><meter min="0" max="650" value={stats.power}/><span>{es?'Peso':'Weight'}</span><meter min="0" max="50" value={stats.mass}/><span>{es?'Agarre':'Grip'}</span><meter min="0" max="1.4" value={stats.grip}/></div><label>{es?'Distancia entre ruedas':'Wheel spacing'}<input aria-label={es?'Distancia entre ruedas':'Wheel spacing'} type="range" min=".75" max="1.35" step=".05" value={g.build.span} onChange={e=>edit({span:Number(e.target.value)})}/></label><label>{es?'Posición del motor: atrás ↔ adelante':'Engine position: rear ↔ front'}<input type="range" min="-.7" max=".7" step=".1" value={g.build.engineX} onChange={e=>edit({engineX:Number(e.target.value)})}/></label><label>{es?'Altura del motor: arriba ↔ abajo':'Engine height: high ↔ low'}<input type="range" min="-.4" max=".5" step=".1" value={g.build.engineY} onChange={e=>edit({engineY:Number(e.target.value)})}/></label><label>{es?'Ruta':'Route'}<select value={route} onChange={e=>setRoute(Number(e.target.value))}>{ROUTES.map((r,i)=><option key={i} value={i}>{r[lang]} · {g.best[i]} m</option>)}</select></label><button type="button" className="cg-primary cg-launch" data-testid="garage-drive" onClick={()=>begin()}>{es?'¡A MANEJAR!':'LET’S DRIVE!'} →</button><div className="cg-two-buttons"><button type="button" onClick={()=>begin(true)}>{es?'Pista de práctica':'Practice track'}</button><button type="button" onClick={()=>{setGarage(current=>({...current,blueprints:[clone(current.build),...current.blueprints.filter(b=>b.name!==current.build.name)].slice(0,8)}));setMessage(es?'Diseño guardado.':'Blueprint saved.');}}>{es?'Guardar diseño':'Save blueprint'}</button></div></aside></div>
 {g.last&&<div className="cg-receipt" role="status"><strong>+{g.last.bolts+g.last.bonus+g.last.challenge} {es?'tornillos':'bolts'}</strong><span>{g.last.distance} m · {es?'Todas tus piezas siguen contigo.':'Every part is still yours.'}</span></div>}
 {target&&!g.owned.includes(target.id)&&<div className="cg-target"><div><small>{es?'MI PRÓXIMA PIEZA':'MY NEXT PART'}</small><strong>{target.name[lang]}</strong></div><progress value={Math.min(g.bolts,target.price)} max={target.price}/><span>{Math.min(g.bolts,target.price)} / {target.price}</span></div>}
 <section className="cg-next-projects" aria-label={es?'Próximos proyectos':'Next projects'}><h3>{es?'Tu próxima aventura':'Your next adventure'}</h3><p>{es?'Premios permanentes. Gana tornillos probando nuevas ideas, sin límites de tiempo.':'Permanent rewards. Earn bolts by trying new ideas, with no time limits.'}</p><div className="cg-project-cards">{GARAGE_PROJECTS.filter(p=>!g.goals.includes(p.id)).slice(0,3).map(p=><article key={p.id}><strong>{p.title[lang]}</strong><p>{p.task[lang]}</p><span>+{p.reward} {es?'tornillos':'bolts'}</span></article>)}{GARAGE_PROJECTS.every(p=>g.goals.includes(p.id))&&<p>{es?'¡Proyectos completos! Sigue construyendo y mejorando tus récords.':'All projects complete! Keep building and beating your own records.'}</p>}</div></section>
 <div className="cg-shop-heading"><div><span className="cg-eyebrow">{es?'HECHAS PARA MEZCLARSE':'MADE TO MIX & MATCH'}</span><h3>{es?'El muro de piezas':'The parts wall'}</h3></div><span>{es?'Sin cajas sorpresa. Elige tu recompensa.':'No mystery boxes. Choose your reward.'}</span></div>
 <div className="cg-categories" aria-label={es?'Tipos de piezas':'Part categories'}>{GROUPS.map((name,i)=><button key={i} type="button" aria-pressed={group===i} onClick={()=>{setGroup(i);setSelected(i*10+1);setExtra(false);}}>{name[lang]}</button>)}</div>
 <div className="cg-parts-filter"><label>{es?'Buscar piezas':'Find parts'}<input type="search" data-testid="garage-part-search" value={query} placeholder={es?'Nombre en cualquier categoría…':'Name in any category…'} onChange={e=>setQuery(e.target.value)}/></label><div className="cg-filter-buttons">{(['all','owned','affordable'] as const).map((value,i)=><button type="button" key={value} data-parts-filter={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{(es?['Todas','Mis piezas','Puedo desbloquear']:['All','My parts','Can unlock'])[i]}</button>)}</div></div>
 <div className="cg-shop-layout"><div className="cg-part-grid">{findGarageParts(g,group,query,filter).map(p=><button type="button" className={`cg-part-card ${selected===p.id?'is-selected':''}`} key={p.id} data-part-id={p.id} aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setGroup(p.group);}}><span className="cg-part-number">{String(p.id).padStart(3,'0')}</span><PartPicture id={p.id}/><strong>{p.name[lang]}</strong><small>{g.owned.includes(p.id)?(g.build.parts.includes(p.id)?(es?'Instalada':'Equipped'):(es?'Tuya':'Owned')):`⬡ ${p.price}`}</small></button>)}{findGarageParts(g,group,query,filter).length===0&&<p className="cg-empty-parts">{es?'No hay piezas con esos filtros. Prueba otra categoría o muestra todas.':'No parts match these filters. Try another category or show all parts.'}</p>}</div><aside className="cg-part-detail"><PartPicture id={selected}/><span className="cg-eyebrow">{part.functional?(es?'PIEZA FUNCIONAL':'FUNCTIONAL PART'):(es?'ESTILO · SIN VENTAJA OCULTA':'STYLE · NO HIDDEN ADVANTAGE')}</span><h3>{part.name[lang]}</h3><p>{part.description[lang]}</p>{(group===4||group===6)&&<label className="cg-inline-check"><input type="checkbox" checked={extra} onChange={e=>setExtra(e.target.checked)}/>{es?'Usar segundo espacio':'Use second slot'}</label>}{owned?<button type="button" className="cg-primary" onClick={()=>{setGarage(current=>equipPart(current,selected,extra));setMessage(es?'Pieza instalada.':'Part fitted.');}}>{es?'Instalar pieza':'Fit this part'}</button>:<><button type="button" className="cg-primary" data-testid="buy-garage-part" disabled={g.bolts<part.price} onClick={()=>{setGarage(current=>buyPart(current,selected));setMessage(es?'¡La pieza es tuya para siempre!':'This part is yours to keep!');}}>{es?'Desbloquear':'Unlock'} · ⬡ {part.price}</button><button type="button" onClick={()=>{setGarage(current=>({...current,target:selected}));setMessage(es?'Nueva meta elegida.':'New target selected.');}}>{es?'Elegir como meta':'Make this my goal'}</button><button type="button" onClick={()=>begin(true,true)}>{es?'Probar gratis':'Free test drive'}</button></>}{[4,5,6,10,11].includes(group)&&g.build.parts[group]!==0&&<button type="button" onClick={()=>{const parts=[...g.build.parts];parts[extra&&group===4?10:extra&&group===6?11:group]=0;edit({parts});}}>{es?'Quitar del auto':'Remove from car'}</button>}{selected===69&&!has(g.build,68)&&<p>{es?'Instala el enganche tortuga en el otro espacio de aventura para remolcar.':'Fit the Turtle Tow Hitch in the other adventure slot to tow.'}</p>}</aside></div>
 <p className="cg-feedback" role="status">{message}</p>
 {g.blueprints.length>0&&<section className="cg-blueprints"><h3>{es?'Mis diseños':'My blueprints'}</h3><div>{g.blueprints.map((b,i)=><button type="button" key={`${b.name}-${i}`} onClick={()=>{edit(b);setSelected(b.parts[1]);setGroup(1);}}><span>{String(i+1).padStart(2,'0')}</span><strong>{b.name}</strong><small>{es?'Cargar diseño':'Load build'} →</small></button>)}</div></section>}
 <details className="cg-projects"><summary>{es?'Proyectos del taller y premios':'Garage projects & rewards'}</summary><p>{es?'Una vez cada uno: 50 m (+20), 150 m (+30), 300 m (+40), salto aterrizado de 8 m (+25), tres aterrizajes (+25), entregar un paquete a 100 m (+30), llegar a 100 m sin perder ruedas (+20).':'Once each: 50 m (+20), 150 m (+30), 300 m (+40), land an 8 m jump (+25), three landings (+25), deliver a parcel at 100 m (+30), reach 100 m without losing a wheel (+20).'}</p><p>{es?'Cada recorrido también da un tornillo por cada 5 metros. Un récord nuevo da 10 más. La práctica no da premios.':'Each drive also earns one bolt per 5 meters. A new personal best adds 10. Practice never pays rewards.'}</p></details>
 <p className="cg-help">{es?'Progreso local en este perfil. Exporta un respaldo desde Ajustes. Física simplificada de juguete; no es un simulador de ingeniería.':'Progress is local to this profile. Export a backup from Settings. Simplified toy physics, not an engineering simulator.'}</p>
 </>}
 </section>;
}
