import {useUnicornArt} from './useUnicornArt';
import {useEffect,useRef,useState} from 'react';
import {ISLANDS,MAGIC} from './catalog';
import {buyMagic,rescueFriend,type KingdomSave} from './save';
import {settleKingdomRide} from './kingdomRewards';
import {makeRide,stepRide,PADS,STARTER_COURSE,type Ride} from './kingdomPhysics';
import {drawKingdom,magicArt,creatureArt,unicornArt} from './kingdomArt';
import {HoldButton,useHeldControls,useReducedMotion} from './controls';
import {useGameSave} from './useGameSave';
import type {Language} from '../types';
import './creative-games.css';
function MagicPicture({id}:{id:number}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current?.getContext('2d');if(!c)return;c.clearRect(0,0,160,110);c.save();c.translate(80,75);c.scale(.64,.64);magicArt(c,id,0,0,160,0);c.restore();},[id]);return <canvas ref={ref} width="160" height="110" aria-hidden="true"/>;}
function KingdomStage({save,island,ride,selected,onRescue,onFinish,language}:{save:KingdomSave;island:number;ride:boolean;selected:number;onRescue:(id:number)=>void;onFinish:(run:Ride)=>void;language:Language}){
 const es=language==='es-MX',ref=useRef<HTMLCanvasElement>(null),run=useRef(makeRide(save.sequence)),reduced=useReducedMotion(),callbacks=useRef({onRescue,onFinish});callbacks.current={onRescue,onFinish};
 const [paused,setPaused]=useState(false),pause=useRef(false),[info,setInfo]=useState({found:0,falls:0,done:false,x:75,y:335,grounded:true}),layout=save.layouts[island],live=useRef({layout,color:save.color,selected});live.current={layout,color:save.color,selected};
 const held=useHeldControls({ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'},()=>{pause.current=true;setPaused(true);},ride);
 useEffect(()=>{const el=ref.current,c=el?.getContext('2d');if(!el||!c)return;let frame=0,last=0,acc=0,ui=0,found=0,finished=false;const draw=(now:number)=>{const dt=last?Math.min((now-last)/1000,.08):0;last=now;const w=el.clientWidth||800,h=el.clientHeight||390,d=Math.min(2,window.devicePixelRatio||1),scale=Math.max(.72,Math.min(1.05,w/800));if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d);}c.setTransform(d*scale,0,0,d*scale,0,0);
  if(ride&&!pause.current){acc+=dt;let steps=0;while(acc>=1/120&&steps++<10){stepRide(run.current,live.current.layout,island,{left:!!held.current.left,right:!!held.current.right,jump:!!held.current.jump});acc-=1/120;}}
  drawKingdom(c,run.current,live.current.layout,island,live.current.color,w/scale,h/scale,ride?null:live.current.selected,reduced.current);
  if(ride){while(found<run.current.found.length){callbacks.current.onRescue(island*3+run.current.found[found]);found++;}if(run.current.completed&&!finished){finished=true;callbacks.current.onFinish(structuredClone(run.current));}ui+=dt;if(ui>.1){ui=0;setInfo({found:run.current.found.length,falls:run.current.falls,done:run.current.completed,x:Math.floor(run.current.x),y:Math.floor(run.current.y),grounded:run.current.grounded});}}
  frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame);},[ride,island]);
 return <><div className="cg-kingdom-stage" data-testid="kingdom-stage" data-world-x={info.x} data-world-y={info.y} data-grounded={info.grounded} data-friends={info.found}><canvas ref={ref} className="cg-kingdom-canvas" role="img" aria-label={es?'Tu jardín mágico con puentes, nubes y una unicornio.':'Your magical garden with bridges, clouds, and a unicorn.'}/>{ride&&<div className="cg-kingdom-hud"><span data-testid="kingdom-friends">{info.found}/3 {es?'amigos encontrados':'friends found'}</span><button type="button" onClick={()=>{pause.current=!pause.current;held.current={};setPaused(pause.current);}}>{paused?(es?'Continuar':'Resume'):(es?'Pausa':'Pause')}</button></div>}{paused&&ride&&!info.done&&<div className="cg-pause-card"><strong>{es?'Tu jardín puede esperar':'Your garden can wait'}</strong><button type="button" onClick={()=>{pause.current=false;setPaused(false);}}>{es?'Continuar aventura':'Continue adventure'}</button></div>}{info.done&&<div className="cg-crash-card cg-kingdom-complete" role="status"><span>{es?'¡LO CREASTE TÚ!':'YOU BUILT THIS!'}</span><h3>{es?'Todos llegaron a casa.':'Everyone made it home.'}</h3><p>{es?'Tus descubrimientos y premios están guardados en este perfil.':'Your discoveries and rewards are saved to this profile.'}</p></div>}</div>
 {ride&&<><div className="cg-controls cg-unicorn-controls"><HoldButton held={held} action="left" label={es?'Mover a la izquierda':'Move left'} disabled={paused||info.done}>←</HoldButton><HoldButton held={held} action="jump" label={es?'Saltar o subir':'Jump or climb'} className="cg-jump" disabled={paused||info.done}>↑ <span>{es?'SALTAR':'JUMP'}</span></HoldButton><HoldButton held={held} action="right" label={es?'Mover a la derecha':'Move right'} disabled={paused||info.done}>→</HoldButton></div><p className="cg-help">{es?'Flechas para moverte; Espacio para saltar. Mantén Saltar junto a una enredadera para subir.':'Arrow keys to move; Space to jump. Hold Jump beside a vine to climb.'} {info.falls>0?(es?'Caer solo te devuelve a la última isla.':'Falling only returns you to the last island.'):''} {info.x>1870&&info.found<3?(es?'Encuentra a los tres amigos antes de entrar al portal.':'Find all three friends before entering the gate.'):''}</p></>}
 </>;
}
function GardenPortrait({color,name,rescued}:{color:number;name:string;rescued:number[]}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current?.getContext('2d');if(!c)return;c.clearRect(0,0,320,170);unicornArt(c,95,155,0,color);rescued.slice(0,5).forEach((id,i)=>creatureArt(c,174+i*28,90-(i%2)*20,Math.floor(id/3)));},[color,rescued.join(',')]);return <canvas ref={ref} width="320" height="170" role="img" aria-label={name}/>;}
export default function RainbowKingdom({close}:{close:()=>void}){
 const {profile,games,setKingdom,saveState}=useGameSave(),k=games.kingdom,language=profile.language,es=language==='es-MX';
 const [selected,setSelected]=useState(0),[magic,setMagic]=useState(1),[ride,setRide]=useState(false),[session,setSession]=useState(0),[undo,setUndo]=useState<number[]|null>(null),[message,setMessage]=useState('');
 const art=useUnicornArt();
 const island=k.island,item=MAGIC[magic-1],canPlace=k.owned.includes(magic),awarded=useRef(false);
 const place=(index:number)=>{setSelected(index);if(!canPlace){setMessage(es?'Desbloquea esta pieza antes de colocarla.':'Unlock this piece before placing it.');return;}setUndo([...k.layouts[island]]);setKingdom(current=>{const layouts=current.layouts.map(row=>[...row]);layouts[island][index]=magic;return {...current,layouts};});setMessage(es?`${item.name[language]} colocada en el lugar ${index+1}.`:`${item.name[language]} placed at spot ${index+1}.`);};
 const start=()=>{awarded.current=false;setKingdom(current=>({...current,sequence:current.sequence+1,lastReward:0}));setSession(n=>n+1);setRide(true);window.scrollTo({top:0,behavior:'auto'});};
 const finish=(run:Ride)=>{if(awarded.current)return;awarded.current=true;setKingdom(current=>settleKingdomRide(current,run,island));};
 if(art.status!=='ready')return <section className="cg-shell cg-kingdom" data-testid="rainbow-kingdom"><header className="cg-topbar"><button type="button" onClick={close}>← {es?'Sala de juegos':'Arcade'}</button><span className="cg-wordmark">BECCA’S <b>RAINBOW KINGDOM</b></span></header><div className="cg-art-loading" role={art.status==='error'?'alert':'status'}><h2>{art.status==='error'?(es?'No se pudo cargar el unicornio':'The unicorn artwork could not load'):(es?'Preparando a tu unicornio…':'Getting your unicorn ready…')}</h2><p>{es?'Tu jardín y tus premios siguen guardados.':'Your garden and rewards remain saved.'}</p>{art.status==='error'&&<button type="button" className="cg-primary" onClick={art.retry}>{es?'Volver a intentar':'Try again'}</button>}</div></section>;
 return <section className="cg-shell cg-kingdom" data-testid="rainbow-kingdom"><header className="cg-topbar"><button type="button" onClick={close}>← {es?'Sala de juegos':'Arcade'}</button><span className="cg-wordmark">BECCA’S <b>RAINBOW KINGDOM</b></span><div className="cg-wallet"><span aria-hidden="true">✿</span><strong data-testid="kingdom-petals">{k.petals}</strong><small>{es?'pétalos':'petals'}</small></div></header>
 {saveState.status==='error'&&<p role="alert" className="cg-save-error">{es?'Este navegador no pudo guardar tu progreso.':'This browser could not save your progress.'}</p>}
 <div className="cg-intro"><div><span className="cg-eyebrow">{es?'CREA LA MAGIA. JUEGA EN ELLA.':'MAKE THE MAGIC. PLAY IN IT.'}</span><h2>{es?'Tu propio':'Your own'}<em>{es?'pequeño reino.':'little kingdom.'}</em></h2><p>{es?'Construye caminos de arcoíris, salta sobre nubes y lleva a tus nuevos amigos a casa.':'Build rainbow paths, bounce on clouds, and bring your new friends home.'}</p></div><GardenPortrait color={k.color} name={k.name} rescued={k.rescued}/></div>
 <div className="cg-kingdom-toolbar"><label>{es?'Mi unicornio':'My unicorn'}<input maxLength={26} value={k.name} onChange={e=>setKingdom(current=>({...current,name:e.target.value}))}/></label><label>{es?'Paleta del unicornio':'Unicorn palette'}<select value={k.color} onChange={e=>setKingdom(current=>({...current,color:Number(e.target.value)}))}>{[es?'Arcoíris':'Rainbow',es?'Turquesa':'Turquoise',es?'Atardecer':'Sunset',es?'Dorado':'Golden'].map((name,i)=><option key={i} value={i}>{name}</option>)}</select></label><label>{es?'Jardín':'Garden'}<select disabled={ride} value={island} onChange={e=>{setUndo(null);setKingdom(current=>({...current,island:Number(e.target.value)}));}}>{ISLANDS.map((name,i)=><option key={i} value={i}>{name[language]}</option>)}</select></label></div>
 <KingdomStage key={`${session}-${island}-${ride}`} save={k} island={island} ride={ride} selected={selected} onRescue={id=>setKingdom(current=>rescueFriend(current,id))} onFinish={finish} language={language}/>
 {ride&&k.lastReward>0&&<div className="cg-discovery" role="status"><strong>+{k.lastReward} {es?'pétalos por completar el recorrido':'petals for completing the ride'}</strong></div>}
 <div className="cg-kingdom-actions">{ride?<button type="button" className="cg-primary" onClick={()=>setRide(false)}>{es?'Volver a construir':'Back to building'}</button>:<><button type="button" className="cg-primary" data-testid="kingdom-ride" onClick={start}>{es?'RECORRER MI AVENTURA':'RIDE MY ADVENTURE'} →</button><button type="button" onClick={()=>{setUndo([...k.layouts[island]]);setKingdom(current=>{const layouts=current.layouts.map(row=>[...row]);layouts[island]=[...STARTER_COURSE];return {...current,layouts};});setMessage(es?'Camino inicial listo. Puedes cambiarlo.':'Starter course ready. Make it your own.');}}>{es?'Preparar camino inicial':'Set up starter course'}</button></>}</div>
 {!ride&&<><p className="cg-build-instruction">{es?'Elige una pieza y toca un lugar numerado para colocarla. Luego recorre lo que construiste.':'Choose a piece, then tap a numbered spot to place it. Then ride what you built.'}</p><div className="cg-pad-grid">{PADS.map((_,i)=><button type="button" key={i} data-build-pad={i} aria-pressed={selected===i} onClick={()=>place(i)}><span>{i+1}</span><small>{k.layouts[island][i]?MAGIC[k.layouts[island][i]-1].name[language]:(es?'Lugar libre':'Open spot')}</small></button>)}</div><div className="cg-two-buttons"><button type="button" disabled={!undo} onClick={()=>{if(!undo)return;const previous=undo;setKingdom(current=>{const layouts=current.layouts.map(row=>[...row]);layouts[island]=previous;return {...current,layouts};});setUndo(null);}}>{es?'Deshacer':'Undo'}</button><button type="button" onClick={()=>{setUndo([...k.layouts[island]]);setKingdom(current=>{const layouts=current.layouts.map(row=>[...row]);layouts[island][selected]=0;return {...current,layouts};});}}>{es?'Quitar pieza seleccionada':'Remove selected piece'}</button></div>
 <div className="cg-shop-heading"><div><span className="cg-eyebrow">{es?'PIEZAS QUE HACEN COSAS':'PIECES THAT DO THINGS'}</span><h3>{es?'Taller de magia':'The magic workshop'}</h3></div><span>{k.owned.length}/12 {es?'piezas tuyas':'pieces owned'}</span></div><div className="cg-magic-grid">{MAGIC.map(p=><button type="button" key={p.id} data-magic-id={p.id} className={`cg-part-card ${magic===p.id?'is-selected':''}`} aria-pressed={magic===p.id} onClick={()=>setMagic(p.id)}><MagicPicture id={p.id}/><strong>{p.name[language]}</strong><small>{k.owned.includes(p.id)?(es?'Tuya · coloca donde quieras':'Owned · place freely'):`✿ ${p.price}`}</small></button>)}</div><div className="cg-magic-detail"><div><h3>{item.name[language]}</h3><p>{item.description[language]}</p></div>{!canPlace&&<button type="button" className="cg-primary" disabled={k.petals<item.price} onClick={()=>setKingdom(current=>buyMagic(current,magic))}>{es?'Desbloquear':'Unlock'} · ✿ {item.price}</button>}</div></>}
 <p className="cg-feedback" role="status">{message}</p><div className="cg-discovery"><strong>{k.rescued.length}/9 {es?'amigos en tu reino':'friends in your kingdom'}</strong><p>{es?'Cada nuevo rescate da 15 pétalos. Completar un jardín por primera vez da 30 más. Cada recorrido completo, incluso repetido, da 15. Tus amigos siempre están bien cuando descansas.':'Each new rescue earns 15 petals. A first garden completion adds 30. Every completed ride, including replays, earns 15. Your friends are always safe when you take a break.'}</p></div><p className="cg-help">{es?'Tu jardín, unicornio, premios y descubrimientos se guardan en este perfil. Los recorridos empiezan de nuevo en el portal. Respalda tu perfil desde Ajustes.':'Your garden, unicorn, rewards, and discoveries save in this profile. Rides restart at the gate. Back up your profile in Settings.'}</p></section>;
}
