import {describe,it,expect} from 'vitest';
import {makeDrive,stepDrive} from './carPhysics';
import {normalizeGames,normalizeDrive,STARTER_BUILD,finishDrive,type Drive} from './save';
import {tickTurbo} from './turbo';
import {findGarageParts,startGarageAttempt,nextRampDistance,landingFeedback,GARAGE_PROJECTS} from './garageExperience';

const gas={gas:true,brake:false,tool:false};
describe('free turbo with honest resource and damage boundaries',()=>{
 it('is ready on the original starter build and needs no new part',()=>{const r=makeDrive(STARTER_BUILD);expect(r.boostCharge).toBe(100);expect(r.build).toEqual(STARTER_BUILD);});
 it('accelerates with the turbo button alone and spends charge',()=>{const a=makeDrive(STARTER_BUILD),b=makeDrive(STARTER_BUILD);for(let i=0;i<180;i++){stepDrive(a,{...gas,gas:false,boost:true});stepDrive(b,gas);}expect(a.x).toBeGreaterThan(b.x+25);expect(a.boostCharge!).toBeLessThan(100);});
 it('depletes rather than providing unlimited boost when held',()=>{const r=makeDrive(STARTER_BUILD);r.vx=100;for(let i=0;i<400;i++)tickTurbo(r,true,false,1/120,true);expect(r.boostCharge).toBe(0);expect(r.boostLocked).toBe(true);expect(r.boostActive).toBe(false);});
 it('recharges only after release while moving on powered wheels',()=>{const r=makeDrive(STARTER_BUILD);r.boostCharge=0;r.boostLocked=true;tickTurbo(r,false,false,1,true);expect(r.boostCharge).toBe(0);r.vx=100;tickTurbo(r,false,false,1,false);expect(r.boostCharge).toBe(0);tickTurbo(r,false,false,1,true);expect(r.boostCharge).toBe(14);expect(r.boostLocked).toBe(false);});
 it('does not spend energy in the air, with brakes held, or after motor loss',()=>{for(const mode of ['air','brake','motor']){const r=makeDrive(STARTER_BUILD);if(mode==='motor')r.broken.push(14);expect(tickTurbo(r,true,mode==='brake',.5,mode!=='air')).toBe(false);expect(r.boostCharge).toBe(100);}});
 it('cannot turn turbo into powered driving after loss of the driven axle',()=>{const r=makeDrive(STARTER_BUILD);r.broken=[0];r.contacts=1;stepDrive(r,{...gas,boost:true});expect(r.boostActive).toBe(false);expect(r.boostCharge).toBe(100);});
 it('does not advance charge during a paused or finished simulation',()=>{const r=makeDrive(STARTER_BUILD);r.boostCharge=30;r.vx=100;stepDrive(r,{...gas,boost:true},0);expect(r.boostCharge).toBe(30);r.ended=true;stepDrive(r,{...gas,boost:true});expect(r.boostCharge).toBe(30);expect(r.distance).toBe(0);});
 it('preserves an empty meter and depletion latch across reload',()=>{const g=normalizeGames(null).garage,r={...makeDrive(STARTER_BUILD),boostCharge:0,boostLocked:true,boostActive:false};const resumed=normalizeDrive(r,g.owned)!;expect(resumed.boostCharge).toBe(0);expect(resumed.boostLocked).toBe(true);});
 it('migrates old drives and clamps malformed resource values',()=>{const g=normalizeGames(null).garage,old={...makeDrive(STARTER_BUILD)};delete old.boostCharge;delete old.boostActive;delete old.boostLocked;expect(normalizeDrive(old,g.owned)!.boostCharge).toBe(100);expect(normalizeDrive({...old,boostCharge:-50},g.owned)!.boostCharge).toBe(0);expect(normalizeDrive({...old,boostCharge:400},g.owned)!.boostCharge).toBe(100);});
 it('keeps the existing starter capable of clearing both ramps without turbo',()=>{for(const track of [0,1,2]){const r=makeDrive(STARTER_BUILD,1,track);for(let i=0;i<7200&&r.x<2250&&!r.ended;i++)stepDrive(r,gas);expect(r.x).toBeGreaterThan(2250);expect(r.ended).toBe(false);}});
});

describe('quick retry, filtering and jump feedback',()=>{
 it('banks once and starts a fresh run from the exact crashed build',()=>{const g={...normalizeGames(null).garage,sequence:1,bolts:10};const r=makeDrive({...g.build,name:'My truck',paint:3});r.distance=180;r.ended=true;r.broken=[0,11];const paid=finishDrive(g,r);const next=startGarageAttempt(g,{track:0,build:r.build,previous:r});expect(next.garage.bolts).toBe(paid.bolts);expect(next.garage.sequence).toBe(2);expect(next.garage.paidThrough).toBe(1);expect(next.run.broken).toEqual([]);expect(next.run.boostCharge).toBe(100);expect(next.run.build).toEqual(r.build);expect(finishDrive(next.garage,r)).toBe(next.garage);expect(next.garage.owned).toEqual(g.owned);});
 it('retains practice mode during retries without paying or changing records',()=>{const g={...normalizeGames(null).garage,sequence:1},r=makeDrive(STARTER_BUILD,1,2,true);r.distance=1000;r.ended=true;const next=startGarageAttempt(g,{track:2,build:r.build,practice:true,previous:r});expect(next.run.practice).toBe(true);expect(next.run.track).toBe(2);expect(next.garage.bolts).toBe(0);expect(next.garage.best).toEqual([0,0,0]);});
 it('unowned test drives and retries never grant or store the preview part',()=>{const g=normalizeGames(null).garage,parts=[...g.build.parts];parts[1]=12;const trial=startGarageAttempt(g,{build:{...g.build,parts},track:0,trial:true});expect(trial.garage).toBe(g);expect(trial.run.id).toBe(0);expect(trial.run.practice).toBe(true);expect(trial.run.build.parts[1]).toBe(12);const next=startGarageAttempt(g,{build:trial.run.build,track:0,trial:true,previous:trial.run});expect(next.garage).toBe(g);expect(next.garage.owned).not.toContain(12);expect(next.run.practice).toBe(true);});
 it('restarting a previously paid drive does not pay the reward again',()=>{const g={...normalizeGames(null).garage,sequence:1},r=makeDrive(STARTER_BUILD);r.distance=200;r.ended=true;const paid=finishDrive(g,r);const next=startGarageAttempt(paid,{track:0,previous:r});expect(next.garage.bolts).toBe(paid.bolts);expect(next.garage.sequence).toBe(2);});
 it('finds parts across categories in either language without accent sensitivity',()=>{const g=normalizeGames(null).garage;expect(findGarageParts(g,0,'lava','all').map(p=>p.id)).toEqual([12]);expect(findGarageParts(g,0,'suspension','all').length).toBeGreaterThan(0);expect(findGarageParts(g,0,'fOsIl','all').map(p=>p.id)).toEqual([15]);});
 it('owned and affordable filters reflect the real wallet',()=>{const g=normalizeGames(null).garage;expect(findGarageParts(g,1,'','owned').map(p=>p.id)).toEqual([11]);expect(findGarageParts(g,1,'','affordable')).toEqual([]);expect(findGarageParts({...g,bolts:50},1,'','affordable').map(p=>p.id)).toEqual([12]);});
 it('does not call a destructive landing a clean jump',()=>{const r=makeDrive(STARTER_BUILD);const before:Drive={...r,air:.5,x:190,launchX:90,landings:0};expect(landingFeedback(before,{...r,x:210,landings:1})).toBe(10);expect(landingFeedback(before,{...r,x:210,landings:1,ended:true})).toBeNull();expect(landingFeedback(before,{...r,x:210,landings:1,broken:[0]})).toBeNull();});
 it('announces ramps ahead rather than already passed ramps',()=>{expect(nextRampDistance(695)).toBe(10);expect(nextRampDistance(815)).toBeGreaterThan(60);expect(nextRampDistance(1540)).toBe(10);expect(nextRampDistance(2700)).toBeGreaterThan(0);});
 it('project cards reflect the unchanged seven-project reward ledger',()=>{expect(GARAGE_PROJECTS.map(p=>[p.id,p.reward])).toEqual([[1,20],[2,30],[3,40],[4,25],[5,25],[6,30],[7,20]]);});
});
