"""Robot parts and kid-friendly content catalogs."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Part:
    id: str
    label: str
    emoji: str
    unlock_stars: int = 0


ROBOT_PARTS: dict[str, tuple[Part, ...]] = {
    "eyes": (
        Part("round", "Friendly Round Eyes", "● ●"),
        Part("square", "Square Scout Eyes", "■ ■", 2),
        Part("star", "Star Eyes", "★ ★", 4),
        Part("sleepy", "Sleepy Eyes", "— —", 6),
        Part("googly", "Googly Eyes", "◉ ◎", 8),
        Part("laser", "Laser Eyes", "◉ ◉", 10),
        Part("pixel", "Pixel Eyes", "▦ ▦", 12),
        Part("heart", "Heart Eyes", "♥ ♥", 16),
        Part("night", "Night-Vision Eyes", "☾ ☾", 20),
        Part("rainbow", "Rainbow Eyes", "🌈 🌈", 24),
        Part("compass", "Compass Eyes", "✥ ✥", 30),
        Part("galaxy", "Galaxy Eyes", "✦ ✦", 38),
    ),
    "mouth": (
        Part("smile", "Friendly Smile", "◡"),
        Part("tiny", "Tiny Beep Mouth", "•", 2),
        Part("zigzag", "Zigzag Mouth", "〰", 4),
        Part("grin", "Big Robot Grin", "▿", 6),
        Part("speaker", "Speaker Mouth", "▥", 8),
        Part("fangs", "Silly Fangs", "▽▽", 10),
        Part("mustache", "Metal Mustache", "〰〰", 13),
        Part("pixel", "Pixel Mouth", "▦", 16),
        Part("rainbow", "Rainbow Smile", "🌈", 20),
        Part("whistle", "Whistle Port", "○", 24),
        Part("dragon", "Dragon Grin", "🐲", 30),
        Part("portal", "Portal Mouth", "🌀", 38),
    ),
    "head": (
        Part("box", "Classic Box Head", "▣"),
        Part("dome", "Space Dome", "◠", 3),
        Part("screen", "Screen Head", "▤", 6),
        Part("antenna", "Rainbow Antenna Head", "⌁", 9),
        Part("crystal", "Crystal Head", "💎", 12),
        Part("cat", "Cat-Ear Head", "🐱", 16),
        Part("knight", "Knight Helmet", "🪖", 20),
        Part("astronaut", "Astronaut Helmet", "🧑‍🚀", 24),
        Part("submarine", "Submarine Dome", "⚓", 28),
        Part("dragon", "Dragon Head", "🐲", 34),
        Part("royal", "Royal Robot Head", "♛", 40),
        Part("portal", "Portal Head", "🌀", 48),
    ),
    "antenna": (
        Part("none", "No Antenna", ""),
        Part("single", "Single Signal Antenna", "📡", 2),
        Part("double", "Double Antenna", "〽️", 4),
        Part("lightbulb", "Idea Bulb Antenna", "💡", 6),
        Part("satellite", "Satellite Dish", "🛰️", 9),
        Part("flower", "Flower Antenna", "🌼", 12),
        Part("propeller", "Tiny Propeller", "🚁", 15),
        Part("lightning", "Lightning Rod", "⚡", 19),
        Part("rainbow", "Rainbow Signal", "🌈", 23),
        Part("crystal", "Crystal Antenna", "🔷", 28),
        Part("moon", "Moon Antenna", "🌙", 34),
        Part("galaxy", "Galaxy Beacon", "🌌", 42),
    ),
    "ears": (
        Part("none", "No Ears", ""),
        Part("round", "Round Audio Dishes", "◉ ◉", 2),
        Part("speaker", "Speaker Ears", "🔊 🔊", 4),
        Part("cat", "Robot Cat Ears", "▲ ▲", 6),
        Part("bunny", "Bunny Receiver Ears", "🐰", 9),
        Part("elf", "Pointed Sensor Ears", "◁ ▷", 12),
        Part("headphones", "Music Headphones", "🎧", 15),
        Part("wing", "Wing Ears", "🪽 🪽", 19),
        Part("radar", "Radar Ears", "📡 📡", 23),
        Part("dragon", "Dragon Ears", "🐲", 28),
        Part("crystal", "Crystal Ears", "💎 💎", 34),
        Part("portal", "Portal Receivers", "🌀 🌀", 42),
    ),
    "shoulders": (
        Part("none", "Plain Shoulders", ""),
        Part("caps", "Round Shoulder Caps", "● ●", 2),
        Part("bolts", "Giant Shoulder Bolts", "🔩 🔩", 4),
        Part("pads", "Adventure Pads", "▰ ▰", 6),
        Part("lights", "Shoulder Lights", "💡 💡", 9),
        Part("wings", "Mini Shoulder Wings", "🪽 🪽", 12),
        Part("rockets", "Shoulder Rockets", "🚀 🚀", 15),
        Part("shield", "Shield Shoulders", "🛡️ 🛡️", 19),
        Part("crystal", "Crystal Shoulders", "💎 💎", 23),
        Part("dragon", "Dragon Spikes", "🐲 🐲", 28),
        Part("cloud", "Cloud Shoulders", "☁️ ☁️", 34),
        Part("galaxy", "Galaxy Shoulders", "🌌 🌌", 42),
    ),
    "arms": (
        Part("grabber", "Grabber Arms", "C C"),
        Part("spring", "Spring Arms", "≋ ≋", 3),
        Part("magnet", "Magnet Hands", "🧲 🧲", 6),
        Part("builder", "Builder Tools", "🔧 🔨", 9),
        Part("giant", "Giant Hands", "✊ ✊", 13),
        Part("stretchy", "Stretchy Arms", "〰 〰", 17),
        Part("wings", "Wing Arms", "◁ ▷", 21),
        Part("shield", "Shield Arms", "🛡️ 🛡️", 25),
        Part("drum", "Drum Arms", "🥁 🥁", 29),
        Part("tentacle", "Tentacle Arms", "🐙 🐙", 33),
        Part("rocket", "Rocket Arms", "🚀 🚀", 39),
        Part("hologram", "Hologram Hands", "✨ ✨", 46),
    ),
    "body": (
        Part("classic_core", "Classic Gear Core", "⚙️"),
        Part("round_core", "Round Power Core", "🔘", 3),
        Part("toolbox", "Toolbox Body", "🧰", 6),
        Part("aquarium", "Aquarium Body", "🐠", 10),
        Part("speaker", "Music Speaker Body", "🎵", 14),
        Part("crystal", "Crystal Body", "💠", 18),
        Part("dinosaur", "Dinosaur Body", "🦖", 22),
        Part("space_suit", "Space-Suit Body", "🪐", 26),
        Part("candy", "Candy Machine Body", "🍬", 30),
        Part("stealth", "Stealth Body", "🥷", 34),
        Part("castle", "Castle Body", "🏰", 40),
        Part("galaxy", "Galaxy Core", "🌌", 48),
    ),
    "chest": (
        Part("none", "Blank Chest Plate", ""),
        Part("star", "Explorer Star", "⭐", 2),
        Part("bolt", "Power Bolt", "⚡", 4),
        Part("heart", "Friendship Heart", "💛", 6),
        Part("paw", "Animal Scout Paw", "🐾", 9),
        Part("monster", "Monster Lab Badge", "👾", 12),
        Part("planet", "Space Planet Badge", "🪐", 15),
        Part("shield", "Hero Shield", "🛡️", 19),
        Part("crown", "Royal Crest", "👑", 23),
        Part("dragon", "Dragon Crest", "🐲", 28),
        Part("portal", "Portal Crest", "🌀", 34),
        Part("galaxy", "Galaxy Medal", "🌌", 42),
    ),
    "base": (
        Part("bronze_wheels", "Bronze Wheels", "◉ ◉"),
        Part("bouncy_legs", "Bouncy Legs", "╱ ╲", 3),
        Part("hover_ball", "Hover Ball", "🔵", 6),
        Part("spider_legs", "Spider Legs", "╱╲╱╲", 9),
        Part("tank_tracks", "Tank Tracks", "▰▰", 12),
        Part("skates", "Speed Skates", "🛼 🛼", 15),
        Part("rocket_boots", "Rocket Boots", "🚀 🚀", 18),
        Part("cloud", "Cloud Floater", "☁️", 22),
        Part("submarine", "Submarine Base", "🌊", 26),
        Part("pogo", "Super Pogo Legs", "🦿 🦿", 30),
        Part("dragon_feet", "Dragon Feet", "🐾 🐾", 36),
        Part("teleport", "Teleport Pad", "🛸", 44),
    ),
    "backpack": (
        Part("none", "No Backpack", ""),
        Part("toolbox", "Tool Backpack", "🧰", 4),
        Part("battery", "Mega Battery", "🔋", 7),
        Part("pet_drone", "Pet Drone", "🛸", 10),
        Part("bubble_tank", "Bubble Tank", "🫧", 13),
        Part("jetpack", "Jetpack", "🚀", 16),
        Part("parachute", "Parachute Pack", "🪂", 20),
        Part("garden", "Tiny Garden", "🌱", 24),
        Part("snack", "Snack Pack", "🍪", 28),
        Part("music", "Music Pack", "🎶", 32),
        Part("portal", "Pocket Portal", "🌀", 38),
        Part("moon", "Moon Base Pack", "🌙", 44),
    ),
    "companion": (
        Part("none", "No Mini Companion", ""),
        Part("orb", "Floating Helper Orb", "🔵", 3),
        Part("bee", "Robo Bee", "🐝", 5),
        Part("butterfly", "Pixel Butterfly", "🦋", 7),
        Part("cat", "Mini Robo Cat", "🐱", 10),
        Part("dog", "Mini Robo Dog", "🐶", 13),
        Part("owl", "Scout Owl Drone", "🦉", 16),
        Part("dragon", "Pocket Dragon", "🐉", 20),
        Part("alien", "Tiny Alien Friend", "👽", 24),
        Part("ghost", "Friendly Holo Ghost", "👻", 28),
        Part("moon", "Moon Sprite", "🌙", 34),
        Part("galaxy", "Galaxy Pet", "🌌", 42),
    ),
    "power": (
        Part("bubble", "Bubble Blaster", "🫧"),
        Part("scanner", "Super Scanner", "🔎", 4),
        Part("magnet", "Magnet Beam", "🧲", 6),
        Part("joke", "Joke Beam", "😂", 8),
        Part("freeze", "Freeze Ray", "❄️", 10),
        Part("music", "Music Pulse", "🎵", 12),
        Part("rainbow", "Rainbow Shield", "🌈", 15),
        Part("invisible", "Invisible Cloak", "👻", 18),
        Part("story", "Story Spark", "📖", 21),
        Part("weather", "Weather Maker", "⛅", 25),
        Part("time", "Time Twister", "⏳", 31),
        Part("friendship", "Friendship Force", "💛", 38),
    ),
    "hat": (
        Part("none", "No Hat", ""),
        Part("cap", "Adventure Cap", "🧢", 3),
        Part("beanie", "Cozy Beanie", "🎿", 5),
        Part("cowboy", "Cowboy Hat", "🤠", 8),
        Part("pirate", "Pirate Hat", "🏴‍☠️", 10),
        Part("crown", "Robot Crown", "👑", 13),
        Part("propeller", "Propeller Hat", "🚁", 16),
        Part("wizard", "Wizard Hat", "🧙", 19),
        Part("astronaut", "Space Helmet", "🪐", 22),
        Part("chef", "Chef Hat", "👨‍🍳", 26),
        Part("detective", "Detective Hat", "🕵️", 30),
        Part("galaxy", "Galaxy Crown", "🌌", 38),
    ),
}

ROBOT_COLORS: dict[str, str] = {
    "Electric Blue": "#3B82F6",
    "Rocket Red": "#EF4444",
    "Sunny Yellow": "#FBBF24",
    "Jungle Green": "#22C55E",
    "Galaxy Purple": "#8B5CF6",
    "Bubblegum Pink": "#EC4899",
    "Silver": "#94A3B8",
    "Midnight Navy": "#1E3A8A",
    "Lava Orange": "#F97316",
    "Mint Green": "#34D399",
    "Aqua Glow": "#06B6D4",
    "Neon Lime": "#84CC16",
    "Royal Gold": "#EAB308",
    "Cosmic Black": "#334155",
    "Cloud White": "#E2E8F0",
    "Coral Blast": "#FB7185",
    "Chocolate Brown": "#92400E",
    "Copper": "#B45309",
    "Ice Blue": "#93C5FD",
    "Hot Magenta": "#D946EF",
    "Emerald": "#059669",
    "Sunset Peach": "#FB923C",
    "Deep Teal": "#0F766E",
    "Violet Glow": "#7C3AED",
}

ROBOT_FINISHES: dict[str, str] = {
    "Matte": "Soft and smooth",
    "Glossy": "Bright showroom shine",
    "Chrome": "Mirror-like metal",
    "Brushed Metal": "Workshop texture",
    "Neon Glow": "Glowing edges",
    "Holographic": "Color-shifting light",
    "Candy": "Sweet translucent shine",
    "Ice": "Frozen crystal look",
    "Lava": "Hot glowing seams",
    "Woodland": "Warm natural panels",
    "Stealth": "Dark low-reflection armor",
    "Rainbow": "Full-spectrum shine",
}

ROBOT_PATTERNS: dict[str, str] = {
    "Solid": "One clean color",
    "Two-Tone": "Split primary and secondary colors",
    "Racing Stripe": "A bold center stripe",
    "Circuit Lines": "Electronic pathways",
    "Stars": "A field of stars",
    "Polka Dots": "Playful dots",
    "Checkerboard": "Fast racing squares",
    "Flames": "Speed flames",
    "Lightning": "Electric bolts",
    "Camouflage": "Adventure camouflage",
    "Hearts": "Friendship hearts",
    "Galaxy": "Deep-space pattern",
}

ROBOT_EYE_GLOWS: dict[str, str] = {
    "Aqua": "#BFFBFF",
    "Lime": "#BEF264",
    "Gold": "#FDE047",
    "Pink": "#F9A8D4",
    "Purple": "#D8B4FE",
    "Red": "#FCA5A5",
    "Orange": "#FDBA74",
    "White": "#FFFFFF",
    "Blue": "#93C5FD",
    "Green": "#86EFAC",
    "Rainbow": "#F0ABFC",
    "Night": "#67E8F9",
}

ROBOT_SIZES: dict[str, float] = {
    "Mini": 0.82,
    "Standard": 1.0,
    "Mega": 1.16,
}

ROBOT_VOICES: dict[str, str] = {
    "Classic Beep": "Beep-boop explorer",
    "Tiny Squeak": "Small and cheerful",
    "Deep Hero": "Bold and brave",
    "Speedy": "Fast-talking adventurer",
    "Sleepy": "Calm and cozy",
    "Musical": "Sings little notes",
    "Space Radio": "Mission-control sound",
    "Pirate Bot": "Arrr-tificial intelligence",
    "Wizard Bot": "Magical and mysterious",
    "Animal Friend": "Gentle forest guide",
    "Comedian": "Always ready with a joke",
    "Royal Announcer": "Grand and dramatic",
}

ROBOT_PERSONALITIES: dict[str, str] = {
    "Curious Explorer": "What can we discover next?",
    "Brave Hero": "Adventure systems ready!",
    "Silly Comedian": "My joke circuits are fully charged!",
    "Gentle Helper": "I am here to help.",
    "Wild Inventor": "Let us build something impossible!",
    "Animal Guardian": "Every creature deserves a friend.",
    "Space Captain": "Prepare for launch!",
    "Mystery Detective": "Clue scanner activated.",
    "Creative Artist": "Let us make the world colorful.",
    "Music Star": "Turn up the robot rhythm!",
    "Sleepy Dreamer": "I dreamed of a moon made of cookies.",
    "Royal Protector": "Nico's World is under friendly protection.",
}

ROBOT_MOODS: tuple[str, ...] = (
    "Happy",
    "Excited",
    "Curious",
    "Brave",
    "Silly",
    "Calm",
    "Proud",
    "Sleepy",
)

ROBOT_PRESETS: dict[str, dict[str, str | int]] = {
    "Classic Buddy": {
        "unlock_stars": 0,
        "head": "box",
        "eyes": "round",
        "mouth": "smile",
        "antenna": "single",
        "ears": "round",
        "shoulders": "caps",
        "arms": "grabber",
        "body": "classic_core",
        "chest": "star",
        "base": "bronze_wheels",
        "backpack": "none",
        "companion": "orb",
        "power": "bubble",
        "hat": "none",
        "color": "Electric Blue",
        "secondary_color": "Sunny Yellow",
        "finish": "Glossy",
        "pattern": "Two-Tone",
        "eye_glow": "Aqua",
        "size": "Standard",
        "voice": "Classic Beep",
        "personality": "Curious Explorer",
    },
    "Forest Ranger": {
        "unlock_stars": 12,
        "head": "cat",
        "eyes": "night",
        "mouth": "smile",
        "antenna": "flower",
        "ears": "cat",
        "shoulders": "pads",
        "arms": "builder",
        "body": "toolbox",
        "chest": "paw",
        "base": "bouncy_legs",
        "backpack": "garden",
        "companion": "owl",
        "power": "scanner",
        "hat": "cap",
        "color": "Jungle Green",
        "secondary_color": "Chocolate Brown",
        "finish": "Woodland",
        "pattern": "Camouflage",
        "eye_glow": "Green",
        "size": "Standard",
        "voice": "Animal Friend",
        "personality": "Animal Guardian",
    },
    "Rocket Captain": {
        "unlock_stars": 20,
        "head": "astronaut",
        "eyes": "star",
        "mouth": "speaker",
        "antenna": "satellite",
        "ears": "radar",
        "shoulders": "rockets",
        "arms": "rocket",
        "body": "space_suit",
        "chest": "planet",
        "base": "rocket_boots",
        "backpack": "jetpack",
        "companion": "alien",
        "power": "weather",
        "hat": "astronaut",
        "color": "Cloud White",
        "secondary_color": "Rocket Red",
        "finish": "Chrome",
        "pattern": "Racing Stripe",
        "eye_glow": "Blue",
        "size": "Mega",
        "voice": "Space Radio",
        "personality": "Space Captain",
    },
    "Joke Machine": {
        "unlock_stars": 10,
        "head": "screen",
        "eyes": "googly",
        "mouth": "grin",
        "antenna": "propeller",
        "ears": "headphones",
        "shoulders": "lights",
        "arms": "spring",
        "body": "candy",
        "chest": "heart",
        "base": "skates",
        "backpack": "snack",
        "companion": "bee",
        "power": "joke",
        "hat": "propeller",
        "color": "Bubblegum Pink",
        "secondary_color": "Sunny Yellow",
        "finish": "Candy",
        "pattern": "Polka Dots",
        "eye_glow": "Gold",
        "size": "Mini",
        "voice": "Comedian",
        "personality": "Silly Comedian",
    },
    "Dragon Guardian": {
        "unlock_stars": 38,
        "head": "dragon",
        "eyes": "galaxy",
        "mouth": "dragon",
        "antenna": "lightning",
        "ears": "dragon",
        "shoulders": "dragon",
        "arms": "shield",
        "body": "dinosaur",
        "chest": "dragon",
        "base": "dragon_feet",
        "backpack": "portal",
        "companion": "dragon",
        "power": "friendship",
        "hat": "crown",
        "color": "Lava Orange",
        "secondary_color": "Cosmic Black",
        "finish": "Lava",
        "pattern": "Flames",
        "eye_glow": "Red",
        "size": "Mega",
        "voice": "Deep Hero",
        "personality": "Brave Hero",
    },
    "Galaxy Wizard": {
        "unlock_stars": 48,
        "head": "portal",
        "eyes": "galaxy",
        "mouth": "portal",
        "antenna": "galaxy",
        "ears": "portal",
        "shoulders": "galaxy",
        "arms": "hologram",
        "body": "galaxy",
        "chest": "galaxy",
        "base": "teleport",
        "backpack": "moon",
        "companion": "galaxy",
        "power": "time",
        "hat": "galaxy",
        "color": "Galaxy Purple",
        "secondary_color": "Aqua Glow",
        "finish": "Holographic",
        "pattern": "Galaxy",
        "eye_glow": "Rainbow",
        "size": "Standard",
        "voice": "Wizard Bot",
        "personality": "Sleepy Dreamer",
    },
}

ANIMATIONS: dict[str, tuple[str, str]] = {
    "wave": ("Wave", "👋"),
    "blink": ("Blink", "😊"),
    "spin": ("Spin", "🔄"),
    "walk": ("Walk", "🛞"),
    "fly": ("Fly", "🚀"),
    "dance": ("Dance", "💃"),
    "flash": ("Flash Lights", "⚡"),
    "bounce": ("Bounce", "🏀"),
    "moonwalk": ("Moonwalk", "🌙"),
    "celebrate": ("Celebrate", "🎉"),
    "charge": ("Power Charge", "🔋"),
}

DEFAULT_ANIMALS: tuple[dict[str, str], ...] = (
    {"name": "Red Panda", "emoji": "🐾", "habitat": "Mountain forests", "fact": "Red pandas use their fluffy tails like warm blankets."},
    {"name": "Axolotl", "emoji": "🦎", "habitat": "Freshwater lakes", "fact": "Axolotls can regrow parts of their limbs."},
    {"name": "Elephant", "emoji": "🐘", "habitat": "Grasslands and forests", "fact": "Elephants communicate with rumbles that travel through the ground."},
    {"name": "Octopus", "emoji": "🐙", "habitat": "Oceans", "fact": "An octopus has three hearts."},
    {"name": "Panda", "emoji": "🐼", "habitat": "Bamboo forests", "fact": "Giant pandas spend much of the day eating bamboo."},
    {"name": "Lion", "emoji": "🦁", "habitat": "Savannas", "fact": "A lion's roar can travel several miles."},
    {"name": "Dolphin", "emoji": "🐬", "habitat": "Oceans and rivers", "fact": "Dolphins use unique whistles a little like names."},
    {"name": "Snowy Owl", "emoji": "🦉", "habitat": "Arctic tundra", "fact": "Snowy owls have feathers covering their feet."},
    {"name": "Capybara", "emoji": "🦫", "habitat": "Wetlands and riverbanks", "fact": "Capybaras are excellent swimmers and can rest in water."},
    {"name": "Fennec Fox", "emoji": "🦊", "habitat": "Sahara Desert", "fact": "Its huge ears help release heat and hear tiny animals underground."},
    {"name": "Mantis Shrimp", "emoji": "🦐", "habitat": "Tropical seas", "fact": "Mantis shrimp can see kinds of light that people cannot."},
    {"name": "Flying Squirrel", "emoji": "🐿️", "habitat": "Forests", "fact": "Flying squirrels glide using a flap of skin between their legs."},
)
