"""Robot parts and kid-friendly content catalogs."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Part:
    id: str
    label: str
    emoji: str
    unlock_stars: int = 0


ROBOT_PARTS: dict[str, tuple[Part, ...]] = {
    "eyes": (
        Part("round", "Friendly Round Eyes", "● ●"),
        Part("square", "Square Scout Eyes", "■ ■", 2),
        Part("star", "Star Eyes", "★ ★", 4),
        Part("sleepy", "Sleepy Eyes", "— —", 6),
        Part("googly", "Googly Eyes", "◉ ◎", 8),
        Part("laser", "Laser Eyes", "◉ ◉", 10),
        Part("pixel", "Pixel Eyes", "▦ ▦", 12),
        Part("heart", "Heart Eyes", "♥ ♥", 16),
        Part("night", "Night-Vision Eyes", "☾ ☾", 20),
        Part("rainbow", "Rainbow Eyes", "🌈 🌈", 24),
        Part("compass", "Compass Eyes", "✥ ✥", 30),
        Part("galaxy", "Galaxy Eyes", "✦ ✦", 38),
    ),
    "head": (
        Part("box", "Classic Box Head", "▣"),
        Part("dome", "Space Dome", "◠", 3),
        Part("screen", "Screen Head", "▤", 6),
        Part("antenna", "Rainbow Antenna", "⌁", 9),
        Part("crystal", "Crystal Head", "💎", 12),
        Part("cat", "Cat-Ear Head", "🐱", 16),
        Part("knight", "Knight Helmet", "🪖", 20),
        Part("astronaut", "Astronaut Helmet", "🧑‍🚀", 24),
        Part("submarine", "Submarine Dome", "⚓", 28),
        Part("dragon", "Dragon Head", "🐲", 34),
        Part("royal", "Royal Robot Head", "♛", 40),
        Part("portal", "Portal Head", "🌀", 48),
    ),
    "arms": (
        Part("grabber", "Grabber Arms", "C C"),
        Part("spring", "Spring Arms", "≋ ≋", 3),
        Part("magnet", "Magnet Hands", "🧲 🧲", 6),
        Part("builder", "Builder Tools", "🔧 🔨", 9),
        Part("giant", "Giant Hands", "✊ ✊", 13),
        Part("stretchy", "Stretchy Arms", "〰 〰", 17),
        Part("wings", "Wing Arms", "◁ ▷", 21),
        Part("shield", "Shield Arms", "🛡️ 🛡️", 25),
        Part("drum", "Drum Arms", "🥁 🥁", 29),
        Part("tentacle", "Tentacle Arms", "🐙 🐙", 33),
        Part("rocket", "Rocket Arms", "🚀 🚀", 39),
        Part("hologram", "Hologram Hands", "✨ ✨", 46),
    ),
    "body": (
        Part("classic_core", "Classic Gear Core", "⚙️"),
        Part("round_core", "Round Power Core", "🔘", 3),
        Part("toolbox", "Toolbox Body", "🧰", 6),
        Part("aquarium", "Aquarium Body", "🐠", 10),
        Part("speaker", "Music Speaker Body", "🎵", 14),
        Part("crystal", "Crystal Body", "💠", 18),
        Part("dinosaur", "Dinosaur Body", "🦖", 22),
        Part("space_suit", "Space-Suit Body", "🪐", 26),
        Part("candy", "Candy Machine Body", "🍬", 30),
        Part("stealth", "Stealth Body", "🥷", 34),
        Part("castle", "Castle Body", "🏰", 40),
        Part("galaxy", "Galaxy Core", "🌌", 48),
    ),
    "base": (
        Part("bronze_wheels", "Bronze Wheels", "◉ ◉"),
        Part("bouncy_legs", "Bouncy Legs", "╱ ╲", 3),
        Part("hover_ball", "Hover Ball", "🔵", 6),
        Part("spider_legs", "Spider Legs", "╱╲╱╲", 9),
        Part("tank_tracks", "Tank Tracks", "▰▰", 12),
        Part("skates", "Speed Skates", "🛼 🛼", 15),
        Part("rocket_boots", "Rocket Boots", "🚀 🚀", 18),
        Part("cloud", "Cloud Floater", "☁️", 22),
        Part("submarine", "Submarine Base", "🌊", 26),
        Part("pogo", "Super Pogo Legs", "🦿 🦿", 30),
        Part("dragon_feet", "Dragon Feet", "🐾 🐾", 36),
        Part("teleport", "Teleport Pad", "🛸", 44),
    ),
    "backpack": (
        Part("none", "No Backpack", ""),
        Part("toolbox", "Tool Backpack", "🧰", 4),
        Part("battery", "Mega Battery", "🔋", 7),
        Part("pet_drone", "Pet Drone", "🛸", 10),
        Part("bubble_tank", "Bubble Tank", "🫧", 13),
        Part("jetpack", "Jetpack", "🚀", 16),
        Part("parachute", "Parachute Pack", "🪂", 20),
        Part("garden", "Tiny Garden", "🌱", 24),
        Part("snack", "Snack Pack", "🍪", 28),
        Part("music", "Music Pack", "🎶", 32),
        Part("portal", "Pocket Portal", "🌀", 38),
        Part("moon", "Moon Base Pack", "🌙", 44),
    ),
    "power": (
        Part("bubble", "Bubble Blaster", "🫧"),
        Part("scanner", "Super Scanner", "🔎", 4),
        Part("magnet", "Magnet Beam", "🧲", 6),
        Part("joke", "Joke Beam", "😂", 8),
        Part("freeze", "Freeze Ray", "❄️", 10),
        Part("music", "Music Pulse", "🎵", 12),
        Part("rainbow", "Rainbow Shield", "🌈", 15),
        Part("invisible", "Invisible Cloak", "👻", 18),
        Part("story", "Story Spark", "📖", 21),
        Part("weather", "Weather Maker", "⛅", 25),
        Part("time", "Time Twister", "⏳", 31),
        Part("friendship", "Friendship Force", "💛", 38),
    ),
    "hat": (
        Part("none", "No Hat", ""),
        Part("cap", "Adventure Cap", "🧢", 3),
        Part("beanie", "Cozy Beanie", "🎿", 5),
        Part("cowboy", "Cowboy Hat", "🤠", 8),
        Part("pirate", "Pirate Hat", "🏴‍☠️", 10),
        Part("crown", "Robot Crown", "👑", 13),
        Part("propeller", "Propeller Hat", "🚁", 16),
        Part("wizard", "Wizard Hat", "🧙", 19),
        Part("astronaut", "Space Helmet", "🪐", 22),
        Part("chef", "Chef Hat", "👨‍🍳", 26),
        Part("detective", "Detective Hat", "🕵️", 30),
        Part("galaxy", "Galaxy Crown", "🌌", 38),
    ),
}

ROBOT_COLORS: dict[str, str] = {
    "Electric Blue": "#3B82F6",
    "Rocket Red": "#EF4444",
    "Sunny Yellow": "#FBBF24",
    "Jungle Green": "#22C55E",
    "Galaxy Purple": "#8B5CF6",
    "Bubblegum Pink": "#EC4899",
    "Silver": "#94A3B8",
    "Midnight Navy": "#1E3A8A",
    "Lava Orange": "#F97316",
    "Mint Green": "#34D399",
    "Aqua Glow": "#06B6D4",
    "Neon Lime": "#84CC16",
    "Royal Gold": "#EAB308",
    "Cosmic Black": "#334155",
    "Cloud White": "#E2E8F0",
    "Coral Blast": "#FB7185",
}

ANIMATIONS: dict[str, tuple[str, str]] = {
    "wave": ("Wave", "👋"),
    "blink": ("Blink", "😊"),
    "spin": ("Spin", "🔄"),
    "walk": ("Walk", "🛞"),
    "fly": ("Fly", "🚀"),
    "dance": ("Dance", "💃"),
    "flash": ("Flash Lights", "⚡"),
    "bounce": ("Bounce", "🏀"),
    "moonwalk": ("Moonwalk", "🌙"),
    "celebrate": ("Celebrate", "🎉"),
    "charge": ("Power Charge", "🔋"),
}

DEFAULT_ANIMALS: tuple[dict[str, str], ...] = (
    {"name": "Red Panda", "emoji": "🐾", "habitat": "Mountain forests", "fact": "Red pandas use their fluffy tails like warm blankets."},
    {"name": "Axolotl", "emoji": "🦎", "habitat": "Freshwater lakes", "fact": "Axolotls can regrow parts of their limbs."},
    {"name": "Elephant", "emoji": "🐘", "habitat": "Grasslands and forests", "fact": "Elephants communicate with rumbles that travel through the ground."},
    {"name": "Octopus", "emoji": "🐙", "habitat": "Oceans", "fact": "An octopus has three hearts."},
    {"name": "Panda", "emoji": "🐼", "habitat": "Bamboo forests", "fact": "Giant pandas spend much of the day eating bamboo."},
    {"name": "Lion", "emoji": "🦁", "habitat": "Savannas", "fact": "A lion's roar can travel several miles."},
    {"name": "Dolphin", "emoji": "🐬", "habitat": "Oceans and rivers", "fact": "Dolphins use unique whistles a little like names."},
    {"name": "Snowy Owl", "emoji": "🦉", "habitat": "Arctic tundra", "fact": "Snowy owls have feathers covering their feet."},
    {"name": "Capybara", "emoji": "🦫", "habitat": "Wetlands and riverbanks", "fact": "Capybaras are excellent swimmers and can rest in water."},
    {"name": "Fennec Fox", "emoji": "🦊", "habitat": "Sahara Desert", "fact": "Its huge ears help release heat and hear tiny animals underground."},
    {"name": "Mantis Shrimp", "emoji": "🦐", "habitat": "Tropical seas", "fact": "Mantis shrimp can see kinds of light that people cannot."},
    {"name": "Flying Squirrel", "emoji": "🐿️", "habitat": "Forests", "fact": "Flying squirrels glide using a flap of skin between their legs."},
)
