import type { Language, StoryRecord } from '../types';
import { STORY_OPTIONS } from './storyBook';
export const STORY_DECISIONS = {
 en:[['Follow the sparkling footprints','Listen for the secret melody'],['Build a clever little helper','Ask a shy creature to join the team']],
 'es-MX':[['Seguir las huellas brillantes','Escuchar la melodía secreta'],['Construir una pequeña ayuda','Invitar a una criatura tímida al equipo']],
} as const;
export const CHAPTER_NAMES = {en:['The impossible invitation','A path with a secret','Something is not quite right','The clue nobody noticed','One brave little idea','A surprise worth sharing'],'es-MX':['La invitación imposible','Un camino con un secreto','Algo no está bien','La pista que nadie vio','Una pequeña gran idea','Una sorpresa para compartir']} as const;
const clues = {
 en:['a trail of warm golden dust ending beneath a leaf','a map folded into the shape of a sneezing frog','three tiny scratches beside a nest','a gear that turned backward whenever anyone shouted','a note that said, “I would like to play, but I am nervous”','a ribbon tangled around a branch above the last clue','a line of little smoky hiccups leading toward a hollow tree','one quiet note trapped inside a silver bell'],
 'es-MX':['un rastro de polvo dorado que terminaba bajo una hoja','un mapa doblado como una rana que estornudaba','tres rayitas junto a un nido','un engranaje que giraba al revés cada vez que alguien gritaba','una nota: “Quiero jugar, pero me da vergüenza”','un listón enredado en una rama sobre la última pista','pequeños hipos de humo que llevaban a un árbol hueco','una nota musical atrapada en una campanita de plata'],
};
const solutions = {
 en:['they lifted the leaf and returned the sleepy light to its lantern','they unfolded the frog-map and drew a clear route home','they built a soft shelter and waited for the egg’s family','they fitted the backward gear into place and tested the bridge together','they invited the shy monster to choose the very first game','they untangled the ribbon and arranged the rescued clues in order','they followed the smoky hiccups until the baby dragon spotted its family','they loosened the bell’s tiny hinge and let the missing note ring out'],
 'es-MX':['levantaron la hoja y devolvieron la luz dormilona a su linterna','desdoblaron el mapa-rana y dibujaron una ruta clara a casa','construyeron un refugio suave y esperaron a la familia del huevo','colocaron el engranaje y probaron el puente juntos','invitaron al monstruo tímido a elegir el primer juego','desenredaron el listón y ordenaron las pistas rescatadas','siguieron los hipos de humo hasta encontrar a la familia del dragón','aflojaron la bisagra de la campanita y dejaron sonar la nota perdida'],
};
export function buildAdventurePages(story:StoryRecord, choices:readonly number[]=[]):string[]{
 const l=story.language,h=story.hero||'Nico',c=story.companion&&story.companion!==h?story.companion:(h==='BoltBot'?'Nico':'BoltBot');
 const item=story.magicItem||STORY_OPTIONS.magicItem[l][0],theme=(story.theme||STORY_OPTIONS.theme[l][0]).toLowerCase(),detail=story.specialDetail?.trim();
 const problemIndex=(STORY_OPTIONS.problem[l] as readonly string[]).indexOf(story.problem),i=problemIndex<0?0:problemIndex;
 const soundPath=choices[0]===1,friendPlan=choices[1]===1;
 if(l==='es-MX')return[
 `¡Toc, toc, PUM! Una carta diminuta entró dando saltitos y aterrizó en el zapato de ${h}. “Se necesita un equipo valiente en ${story.place}”, decía. Abajo había una advertencia: “Traer curiosidad. Las galletas son opcionales”. ${h} llamó a ${c}. “¿Una aventura de verdad?” “Eso espero. ¡Mi mochila ya está emocionada!” Dentro guardaron ${item}. La carta dio una última voltereta y señaló el camino. Algo pequeño los esperaba. Algo que no podía resolver el misterio sin ayuda.`,
 `El camino hacia ${story.place} brillaba como si alguien hubiera derramado estrellas. ${c} encontró dos señales: una mostraba huellas relucientes y la otra, una nota musical. “Podemos seguir las huellas o escuchar”, dijo ${h}. Un caracol con sombrero apareció detrás de una piedra. “Yo elegiría las galletas”, anunció. Los amigos rieron. Después se quedaron muy quietos. El objeto especial vibró en la mochila. Había una pista cerca. ¿Qué camino debía elegir el equipo?`,
 `${soundPath?'Siguieron una melodía suave. Cada vez que el viento dejaba de soplar, una campanita respondía desde lejos.':'Siguieron las huellas brillantes. La más pequeña parecía haberse detenido para bailar alrededor de una margarita.'} Al llegar descubrieron que ${story.problem}. “Primero observemos”, propuso ${h}. Encontraron ${clues[l][i]}. ${c} intentó moverlo todo a la vez. ¡Clinc! Un sombrero cayó sobre sus ojos. “Ahora veo el misterio muy oscuro”. La risa les ayudó a respirar. Pero todavía faltaba la pista principal.`,
 `${detail?`${detail.replace(/[.!?]+$/,'')}. `:''}${h} se agachó y examinó ${item}. “No necesitamos correr. Necesitamos comprender”. ${c} vio una marca que antes parecía una mancha. Encajaba con la pista. “¡Es una instrucción!” Podían construir una pequeña ayuda o invitar a una criatura tímida que los observaba desde un rincón. Las dos ideas exigían ${theme}. El equipo comparó lo que sabía. Esta vez no adivinaría a lo loco. Tenía un plan, una pista y espacio para una amistad más.`,
 `${friendPlan?'“¿Quieres ayudarnos?”, preguntaron. La criatura salió despacito y señaló un detalle que nadie había visto.':'Con cuidado construyeron una pequeña ayuda usando lo que habían encontrado. La primera prueba hizo un ruido parecido a un hipo; ajustaron una pieza y probaron otra vez.'} Entonces ${problemIndex<0?'usaron la nueva pista para preparar una solución segura y probarla juntos':solutions[l][i]}. Durante un segundo no ocurrió nada. ${h} y ${c} se miraron. Luego llegó un destello, una risa y un “¡Lo logramos!” tan alegre que el caracol levantó el sombrero.`,
 `Al final, ${story.ending}. “Mi parte favorita no fue acertar a la primera”, dijo ${h}. “Fue descubrir que podíamos volver a intentarlo”. ${c} guardó ${item} con mucho cuidado. Habían aprendido algo sobre ${theme}, y también que los misterios se vuelven menos grandes cuando se comparten. Justo al regresar apareció otra carta. Esta vez llevaba una huella diminuta y una sola pregunta: “¿Mañana?” El caracol ya estaba preparando su mochila. Y sí: ahora llevaba galletas.`,
 ];
 return[
 `Tap, tap, THUMP! A tiny letter bounced through the doorway and landed on ${h}’s shoe. “A brave team is needed at ${story.place},” it said. Underneath was a warning: “Bring curiosity. Cookies are optional.” ${h} called ${c}. “A real adventure?” “I hope so. My backpack is already excited!” They packed ${item}. The letter did one last somersault and pointed toward the path. Something small was waiting there. Something that could not solve this mystery alone.`,
 `The road to ${story.place} shimmered as if somebody had spilled a pocketful of stars. ${c} found two signs: one showed sparkling footprints; the other showed a musical note. “We could follow the prints or listen,” said ${h}. A snail in a hat peeked around a stone. “I would follow the cookies,” it announced. The friends laughed, then stood very still. Their special item trembled inside the backpack. A clue was close. Which path should the team choose?`,
 `${soundPath?'They followed a soft melody. Whenever the wind stopped, a little bell answered from far away.':'They followed the sparkling footprints. The smallest print seemed to have stopped for a dance around a daisy.'} When they arrived, they discovered that ${story.problem}. “Let’s look before we leap,” said ${h}. They found ${clues[l][i]}. ${c} tried moving everything at once. CLINK! A hat dropped over their eyes. “Well, now the mystery looks very dark.” Laughing helped them take a breath. But the most important clue was still missing.`,
 `${detail?`${detail.replace(/[.!?]+$/,'')}. `:''}${h} knelt beside ${item}. “We don’t need to rush. We need to understand.” ${c} noticed a mark that had looked like a smudge. It matched the clue. “It’s an instruction!” They could build a little helper or invite the shy creature watching from a corner. Either plan would take ${theme}. The team compared what it knew. This time, it would not simply guess. It had a plan, a clue, and room for one more friend.`,
 `${friendPlan?'“Would you help us?” they asked. The shy creature stepped forward and pointed out a detail everyone else had missed.':'They carefully built a little helper from the things they had found. Its first test made a noise like a hiccup. They adjusted one piece and tried again.'} Then ${problemIndex<0?'they used the new clue to prepare a safe solution and test it together':solutions[l][i]}. For one breath, nothing happened. ${h} and ${c} looked at each other. Then came a sparkle, a laugh, and a delighted “We did it!” The snail lifted its hat in celebration.`,
 `In the end, ${story.ending}. “My favorite part wasn’t getting everything right the first time,” said ${h}. “It was finding out that we could try again.” ${c} carefully packed ${item}. They had learned something about ${theme}, and something else: a shared mystery feels smaller. Just as they reached home, another letter arrived. This one carried a tiny footprint and a single question: “Tomorrow?” The snail was already packing its backpack. And yes, this time it was bringing cookies.`,
 ];
}
export function storyImage(story:StoryRecord,page:number):string|undefined{
 const art=import.meta.glob('../assets/art/story-*.webp',{eager:true,query:'?url',import:'default'}) as Record<string,string>;
 const place=story.place.toLowerCase(),family=/dino/.test(place)?'dino':/moon|lunar/.test(place)?'moon':/forest|bosque|cloud|nubes/.test(place)?'rainbow':/cave|cueva|castle|castillo/.test(place)?'castle':'star';
 return art[`../assets/art/story-${family}-${Math.max(1,Math.min(6,page+1))}.webp`];
}
export const readingPrompt=(page:number,language:Language)=> (language==='es-MX'?['¿Qué podría traer la carta?','¿Qué pista seguirías tú?','¿Qué detalle podría ser importante?','¿A quién pedirías ayuda?','¿Qué cambió cuando probaron otra vez?','¿Qué aventura te gustaría inventar después?']:['What might the letter bring?','Which clue would you follow?','Which detail might matter?','Who would you ask for help?','What changed when they tried again?','What adventure would you invent next?'])[page];
