import {useEffect,useMemo,useRef,useState} from 'react';
import {mergeAnimalLibrary} from '../FeatureArt';
import {localizeAnimalCompat} from '../i18n/animalsCompat';
import type {LocalProfile,MovieProject,MoviePose} from '../types';
import type {RenderableMovieCharacter} from './movieRenderer';
import showtimeData from '../catalogs/showtime.json';
import {FORMATS,freshShots,MOVIE_SCENES,MOVIE_TEMPLATES,moveShot,movieTemplate,normalizeShots,projectShots,shotAt} from './director';
import type {MovieFormat,Shot} from './director';
import {disposeDirectorArt,loadDirectorArt} from './directorArt';
import type {DirectorArt} from './directorArt';
import {drawDirectorFrame} from './directorRenderer';
import {canRecordCanvasMovie,downloadMovieBlob,recordCanvasMovie} from './recordMovie';
import {NarrationControls,useNarration} from '../nico/Narration';
import './director-studio.css';
type Props={profile:LocalProfile;nicoBaseSource?:string;nicoOutfitSource?:string;initialProject?:MovieProject|null;onProjectSaved:(project:MovieProject)=>void;onProjectDownloaded:(id:string,mime:string)=>void};
const uid=()=>`movie-${globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2)}`;
const key=(c:{kind:string;id:string})=>`${c.kind}:${c.id}`;
export function ShowtimeStudio({profile,initialProject,onProjectSaved,onProjectDownloaded}:Props){
 const es=profile.language==='es-MX',narrator=useNarration(profile.language,profile.nico.speechEnabled);
 const cast=useMemo<RenderableMovieCharacter[]>(()=>[{key:'nico:nico',kind:'nico',id:'nico',name:'Nico'},{key:'friend:becca',kind:'friend',id:'becca',name:'Becca'},{key:'friend:lua',kind:'friend',id:'lua',name:'Lua'},
 {key:`robot:${profile.robot.id}`,kind:'robot',id:profile.robot.id,name:profile.robot.name,robot:profile.robot},...profile.monsters.map(monster=>({key:`monster:${monster.id}`,kind:'monster' as const,id:monster.id,name:monster.name,monster})),...profile.pets.map(pet=>({key:`pet:${pet.id}`,kind:'pet' as const,id:pet.id,name:pet.name,pet})),...mergeAnimalLibrary(profile.animals).map(animal=>({key:`animal:${animal.id}`,kind:'animal' as const,id:animal.id,name:localizeAnimalCompat(animal,profile.language).name,animal}))],[profile.robot,profile.monsters,profile.pets,profile.animals,profile.language]);
 const [selected,setSelected]=useState(()=>initialProject?.characters.map(key)??['nico:nico','friend:becca']),[shots,setShots]=useState<Shot[]>(()=>projectShots(initialProject));
 const [title,setTitle]=useState(initialProject?.title??(es?'Mi gran aventura':'My Great Adventure')),[caption,setCaption]=useState(initialProject?.caption??''),[format,setFormat]=useState<MovieFormat>(initialProject?.format??'wide');
 const [shotIndex,setShotIndex]=useState(0),[scrub,setScrub]=useState(0),[playing,setPlaying]=useState(false),[recording,setRecording]=useState(false),[progress,setProgress]=useState(0),[parentConfirmed,setParentConfirmed]=useState(false),[query,setQuery]=useState('');
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0),[video,setVideo]=useState<{url:string;blob:Blob;project:MovieProject}|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),art=useRef<DirectorArt|null>(null),abort=useRef<AbortController|null>(null),alive=useRef(true),projectId=useRef(initialProject?.id??uid()),snapshot=useRef('');
 const chosen=useMemo(()=>selected.flatMap(k=>cast.find(c=>c.key===k)??[]),[cast,selected]);
 const duration=shots.reduce((v,s)=>v+s.durationMs,0),activeShot=shots[Math.min(shotIndex,shots.length-1)];
 const latest=useRef({shots,chosen,title,caption,scrub});latest.current={shots,chosen,title,caption,scrub};
 const artKey=JSON.stringify([chosen.map(c=>[c.key,c.monster?.body,c.pet?.species]),profile.nico.profession,[...new Set(shots.map(s=>s.background))].sort(),retry]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort();disposeDirectorArt(art.current);};},[]);
 useEffect(()=>{if(!video)return;return()=>URL.revokeObjectURL(video.url);},[video]);
 const render=(time:number)=>{if(!canvas.current||!art.current)return;const v=latest.current,frame=shotAt(time,v.shots);drawDirectorFrame(canvas.current,art.current,v.chosen,v.shots[frame.index],frame.progress,v.title,v.caption);canvas.current.dataset.movieFrame=String(frame.index);canvas.current.dataset.renderer='canvas2d';};
 useEffect(()=>{let cancelled=false;setReady(false);setError('');disposeDirectorArt(art.current);art.current=null;
  void loadDirectorArt(chosen,profile.nico.profession,shots.map(s=>s.background??'star-stage')).then(result=>{if(cancelled){disposeDirectorArt(result);return;}art.current=result;setReady(true);render(latest.current.scrub);}).catch(()=>{if(!cancelled)setError(es?'No se pudo cargar un personaje. Reintenta antes de grabar.':'A character could not load. Retry before recording.');});return()=>{cancelled=true;};
 },[artKey]);
 useEffect(()=>{if(!playing&&!recording)render(scrub);},[scrub,format,ready,title,caption,shots,playing,recording]);
 useEffect(()=>{setVideo(null);setNotice('');setPlaying(false);},[shots,title,caption,format,selected]);
 useEffect(()=>{if(!playing||!ready)return;let frame=0,timer=0,last=0;const start=performance.now(),base=scrub;const tick=()=>{frame=0;const now=performance.now();if(now-last<1000/24){schedule();return;}last=now;const time=Math.min(duration,base+now-start);render(time);setScrub(time);if(time>=duration){setPlaying(false);return;}schedule();};const schedule=()=>{timer=window.setTimeout(()=>{frame=requestAnimationFrame(tick);},42);};schedule();return()=>{clearTimeout(timer);cancelAnimationFrame(frame);};},[playing,ready]);
 useEffect(()=>{const hide=()=>{if(document.hidden){setPlaying(false);abort.current?.abort();narrator.stop();}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 const project=():MovieProject=>({id:projectId.current,title:title.trim().slice(0,48)||(es?'Mi película':'My Movie'),characters:chosen.map(({kind,id,name})=>({kind,id,name})),poseSequence:normalizeShots(shots),background:shots[0]?.background??'star-stage',caption:caption.slice(0,140),language:profile.language,durationMs:duration,createdAt:initialProject?.createdAt??new Date().toISOString(),directorVersion:1,format});
 const saveProject=()=>{if(!chosen.length)return;const p=project();onProjectSaved(p);setNotice(es?'Proyecto guardado. Puedes editarlo de nuevo en Mis películas.':'Project saved. Reopen it in My Movies to keep editing.');};
 const makeVideo=async()=>{if(!canvas.current||!ready||!chosen.length||!parentConfirmed||recording)return;narrator.stop();setPlaying(false);setVideo(null);setError('');setRecording(true);setProgress(0);const controller=new AbortController();abort.current=controller;const p=project();snapshot.current=JSON.stringify(p);
  try{const result=await recordCanvasMovie({canvas:canvas.current,durationMs:duration,fps:24,drawFrame:render,onProgress:v=>{if(alive.current)setProgress(v);},signal:controller.signal});if(!alive.current)return;const saved={...p,lastMimeType:result.mimeType};onProjectSaved(saved);setVideo({url:URL.createObjectURL(result.blob),blob:result.blob,project:saved});setNotice(es?'Tu película está lista. El video no se ha subido a ningún servidor.':'Your movie is ready. No video was uploaded.');}catch(e){if(alive.current)setError(e instanceof DOMException&&e.name==='AbortError'?(es?'Grabación cancelada; tu proyecto sigue aquí.':'Recording cancelled; your project is still here.'):(es?'No se pudo terminar el video en este navegador. Guarda el proyecto para intentarlo de nuevo.':'This browser could not finish the video. Save the project and try again.'));}finally{abort.current=null;if(alive.current){setRecording(false);setProgress(0);render(scrub);}}
 };
 const patchShot=(patch:Partial<Shot>)=>setShots(old=>normalizeShots(old.map((s,i)=>i===shotIndex?{...s,...patch}:s)));
 const jump=(i:number)=>{setPlaying(false);setShotIndex(i);setScrub(shots.slice(0,i).reduce((n,s)=>n+s.durationMs,0));};
 const applyTemplate=(id:typeof MOVIE_TEMPLATES[number])=>{const next=movieTemplate(id,profile.language);setShots(next.shots);setTitle(next.title);setShotIndex(0);setScrub(0);};
 const dimensions=FORMATS[format],available=canRecordCanvasMovie();
 return <section className="showtime-studio director-studio" aria-labelledby="showtime-title" data-recording={recording}>
  <header className="nico-feature-heading"><div><small>{es?'TU PEQUEÑO ESTUDIO DE CINE':'YOUR LITTLE FILM STUDIO'}</small><h2 id="showtime-title">{es?'Estudio Showtime':'Showtime Studio'}</h2><p>{es?'Dirige a Nico y sus amigos. Elige el reparto, cambia escenarios, ordena tomas y crea una película en este dispositivo.':'Direct Nico and friends. Cast your characters, change locations, arrange shots, and make a movie on this device.'}</p></div></header>
  <div className="director-layout"><section className="director-screen"><canvas ref={canvas} width={dimensions.width} height={dimensions.height} data-testid="movie-canvas" aria-label={es?'Vista previa del video':'Movie preview'} style={{aspectRatio:`${dimensions.width}/${dimensions.height}`}}/>
   {!ready&&<p role="status">{error||(es?'Preparando el reparto…':'Preparing the cast…')}</p>}{error&&<><p role="alert">{error}</p>{!ready&&<button onClick={()=>setRetry(n=>n+1)} type="button">{es?'Reintentar':'Retry'}</button>}</>}
   <div className="director-transport"><button type="button" data-testid="movie-preview" disabled={!ready||recording} onClick={()=>{narrator.stop();if(scrub>=duration)setScrub(0);setPlaying(v=>!v);}}>{playing?(es?'Pausar':'Pause'):(es?'Reproducir':'Play preview')}</button><label className="sr-only" htmlFor="movie-scrub">{es?'Posición del video':'Movie position'}</label><input id="movie-scrub" type="range" min="0" max={duration} step="100" value={Math.min(scrub,duration)} disabled={recording} onChange={e=>{setPlaying(false);setScrub(Number(e.target.value));}}/><output>{(scrub/1000).toFixed(1)} / {duration/1000}s</output></div>
   <p className="director-private">{es?'Video silencioso con subtítulos. La voz de lectura se oye en la app, no se graba. Sin cámara, micrófono ni subidas.':'Silent video with captions. Read-aloud plays in the app and is not recorded. No camera, microphone, or uploads.'}</p>
   {recording?<div role="status"><progress value={progress} max="1"/><button type="button" onClick={()=>abort.current?.abort()}>{es?'Cancelar grabación':'Cancel recording'}</button></div>:<div className="director-export"><button type="button" data-testid="movie-save" disabled={!chosen.length} onClick={saveProject}>{es?'Guardar proyecto':'Save project'}</button><label><input type="checkbox" checked={parentConfirmed} onChange={e=>setParentConfirmed(e.target.checked)}/>{es?'Un adulto ayuda con la grabación y descarga.':'A grown-up is helping with recording and download.'}</label><button type="button" data-testid="movie-record" disabled={!available||!ready||!chosen.length||!parentConfirmed} onClick={()=>void makeVideo()}>{es?'Crear video':'Make Video'}</button>{!available&&<p>{es?'Este navegador admite la vista previa y los proyectos, pero no la grabación.':'This browser supports preview and projects, but not recording.'}</p>}</div>}
   <p role="status">{notice}</p>{video&&<div className="director-result"><video src={video.url} controls playsInline preload="metadata" aria-label={es?'Tu película terminada':'Your finished movie'}/><button type="button" data-testid="movie-download" onClick={()=>{downloadMovieBlob(video.blob,video.project.title);onProjectDownloaded(video.project.id,video.blob.type);}}>{es?'Descargar película':'Download movie'} {video.blob.type.includes('mp4')?'.mp4':'.webm'}</button></div>}
  </section>
  <fieldset className="director-editor" disabled={recording}><legend>{es?'Mesa de dirección':'Director’s desk'}</legend>
   <div className="director-templates">{MOVIE_TEMPLATES.map(id=><button type="button" key={id} data-movie-template={id} onClick={()=>applyTemplate(id)}>{id==='space-rescue'?(es?'Rescate espacial':'Space rescue'):id==='forest-friends'?(es?'Amigos del bosque':'Forest friends'):(es?'Fiesta monstruosa':'Monster party')}</button>)}</div>
   <label>{es?'Título':'Movie title'}<input value={title} maxLength={48} onChange={e=>setTitle(e.target.value)}/></label>
   <label>{es?'Formato':'Format'}<select value={format} onChange={e=>setFormat(e.target.value as MovieFormat)}><option value="wide">{es?'Cine horizontal':'Widescreen'}</option><option value="square">{es?'Cuadrado':'Square'}</option><option value="portrait">{es?'Vertical':'Portrait'}</option></select></label>
   <details className="director-cast" open><summary>{es?'Reparto':'Cast'} · {chosen.length}/3</summary><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?'Buscar personaje…':'Find a character…'} aria-label={es?'Buscar personaje':'Search cast'}/><div className="director-cast__list">{cast.filter(c=>!query||c.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(c=><button type="button" key={c.key} data-movie-character={c.key} aria-pressed={selected.includes(c.key)} disabled={!selected.includes(c.key)&&chosen.length>=3} onClick={()=>setSelected(old=>old.includes(c.key)?old.filter(k=>k!==c.key):old.length<3?[...old,c.key]:old)}>{c.name}</button>)}</div></details>
   <div className="director-timeline" role="group" aria-label={es?'Tomas de la película':'Movie shots'}>{shots.map((s,i)=><button type="button" key={i} data-movie-shot={i} aria-pressed={shotIndex===i} onClick={()=>jump(i)}><b>{i+1}</b><span>{showtimeData.poses.find(p=>p.id===s.pose)?.name[profile.language]}</span><small>{s.durationMs/1000}s</small></button>)}</div>
   <div className="director-shot-actions"><button type="button" disabled={shotIndex===0} onClick={()=>{setShots(old=>moveShot(old,shotIndex,-1));setShotIndex(i=>i-1);}}>{es?'Antes':'Earlier'} ←</button><button type="button" disabled={shotIndex>=shots.length-1} onClick={()=>{setShots(old=>moveShot(old,shotIndex,1));setShotIndex(i=>i+1);}}>{es?'Después':'Later'} →</button><button type="button" disabled={shots.length>=8||duration>=23500} onClick={()=>{setShots(old=>normalizeShots([...old,{...activeShot}]));}}>{es?'Duplicar':'Duplicate'}</button><button type="button" disabled={shots.length<=1} onClick={()=>{setShots(old=>old.filter((_,i)=>i!==shotIndex));setShotIndex(Math.max(0,shotIndex-1));setScrub(0);}}>{es?'Quitar toma':'Remove shot'}</button></div>
   <label>{es?'Acción':'Action'}<select value={activeShot.pose} onChange={e=>patchShot({pose:e.target.value as MoviePose})}>{showtimeData.poses.map(p=><option key={p.id} value={p.id}>{p.name[profile.language]}</option>)}</select></label>
   <label>{es?'Escenario de esta toma':'This shot’s location'}<select value={activeShot.background} onChange={e=>patchShot({background:e.target.value})}>{showtimeData.scenes.map(s=><option key={s.id} value={s.id}>{s.name[profile.language]}</option>)}</select></label>
   <label>{es?'Duración de toma':'Shot length'}<select value={activeShot.durationMs} onChange={e=>patchShot({durationMs:Number(e.target.value)})}>{[...new Set([activeShot.durationMs,1000,1500,2000,2500,3000,4000,5000,6000])].sort((a,b)=>a-b).map(d=><option key={d} value={d}>{d/1000}s</option>)}</select></label>
   <label>{es?'Cámara':'Camera'}<select value={activeShot.camera??'wide'} onChange={e=>patchShot({camera:e.target.value==='close'?'close':'wide'})}><option value="wide">{es?'Plano amplio':'Wide shot'}</option><option value="close">{es?'Acercamiento':'Close backdrop'}</option></select></label>
   <label>{es?'Texto de esta toma':'This shot’s caption'}<textarea maxLength={140} value={activeShot.caption??''} onChange={e=>patchShot({caption:e.target.value})}/></label>
   <label>{es?'Texto para tomas sin subtítulo':'Caption for shots without one'}<input maxLength={140} value={caption} onChange={e=>setCaption(e.target.value)}/></label>
   <button type="button" disabled={!profile.nico.speechEnabled} onClick={()=>narrator.speak([{text:activeShot.caption||caption}])}>{es?'Leer subtítulo':'Read caption aloud'}</button><NarrationControls narrator={narrator} language={profile.language}/>
   <small>{es?'Hasta 8 tomas y 24 segundos. Tu proyecto guarda instrucciones, no archivos de video.':'Up to 8 shots and 24 seconds. Projects store instructions, not video files.'}</small>
  </fieldset></div>
 </section>;
}
