import {describe,expect,it} from 'vitest';
import {FORMATS,freshShots,moveShot,movieTemplate,MOVIE_TEMPLATES,normalizeShots,projectShots,shotAt} from './director';
import {normalizeStore} from '../storage';
import type {MovieProject} from '../types';
const saved=(project:unknown)=>normalizeStore({profiles:[{id:'child',playerName:'Nico',movieProjects:[project]}],activeProfileId:'child'}).profiles[0].movieProjects[0];
describe('Movie director',()=>{
 it('provides three real multiscene stories and correct frame boundaries',()=>{for(const id of MOVIE_TEMPLATES)for(const l of ['en','es-MX'] as const){const t=movieTemplate(id,l);expect(t.shots).toHaveLength(4);expect(new Set(t.shots.map(s=>s.background)).size).toBeGreaterThan(1);expect(t.shots.every(s=>s.caption&&s.caption.length<=140)).toBe(true);}const s=freshShots();expect(shotAt(0,s).index).toBe(0);expect(shotAt(2000,s).index).toBe(1);expect(shotAt(6000,s).index).toBe(2);expect(shotAt(Infinity,s).progress).toBe(0);});
 it('normalizes only valid scenes/poses and caps the frame workload',()=>{const rows=normalizeShots([...Array(12)].map(()=>({pose:'dance',durationMs:999999,background:'https://foreign.example/video',caption:'X'.repeat(500),camera:'close'})));expect(rows.length).toBe(4);expect(rows.reduce((n,r)=>n+r.durationMs,0)).toBe(24000);expect(rows.every(s=>s.background==='star-stage'&&s.caption!.length===140)).toBe(true);expect(normalizeShots([null,{pose:'not-real'}])).toEqual([]);expect(projectShots({poseSequence:[],background:'bad'} as unknown as MovieProject)).toHaveLength(3);for(const f of Object.values(FORMATS))expect(f.width*f.height).toBeLessThanOrEqual(960*640);});
 it('reorders without mutating the project',()=>{const s=freshShots(),m=moveShot(s,0,1);expect(m[0].pose).toBe('dance');expect(s[0].pose).toBe('wave');expect(moveShot(s,0,-1)).toEqual(s);});
 it('persists shot captions, backgrounds, camera, duration, format and friend cast',()=>{const t=movieTemplate('space-rescue','en');const project={id:'a',title:t.title,poseSequence:t.shots,characters:[{kind:'nico',id:'nico',name:'Nico'},{kind:'friend',id:'becca',name:'Becca'}],background:'star-stage',durationMs:10000,directorVersion:1,format:'portrait',language:'en',createdAt:'2026-09-05T00:00:00Z',videoBlob:'do not keep'};const one=saved(project);expect(one.poseSequence).toEqual(normalizeShots(t.shots));expect(one.durationMs).toBe(10000);expect(one.format).toBe('portrait');expect(one.characters[1].kind).toBe('friend');expect((one as unknown as Record<string,unknown>).videoBlob).toBeUndefined();expect(saved(one)).toEqual(one);});
 it('keeps old projects readable without changing their existing export length',()=>{const p=saved({id:'legacy',title:'Old movie',characters:[{kind:'robot',id:'bolt',name:'Bolt'}],poseSequence:[{pose:'wave',durationMs:1200},{pose:'dance',durationMs:1200}],durationMs:6000,background:'jungle',language:'en'});expect(p.directorVersion).toBeUndefined();expect(p.durationMs).toBe(6000);expect(projectShots(p)[0].background).toBe('jungle');});
});
